<?php 

  return [
  '5883102' => [
 "calgary"=>"Калгарі",
"edmonton"=>"Едмонтон",
"fort-mcmurray"=>"Форт МакМеррей",
"lethbridge"=>"Летбрідж",
"medicine-hat"=>"Медісін Хат",
"red-deer"=>"Ред Дір",
"sherwood-park"=>"Шервуд Парк",
"st-albert"=>"Сент Альберт",
 ], 
 '5909050' => [
 "abbotsford"=>"Абботсфорд",
"anmore"=>"Канмор",
"burnaby"=>"Бернабі",
"chilliwack"=>"Чилівак",
"coquitlam"=>"Кокуїтлам",
"delta"=>"Дельта",
"kamloops"=>"Камлупс",
"kelowna"=>"Келоуна",
"langley"=>"Ленглі",
"maple-ridge"=>"Мейпл Рідж",
"nanaimo"=>"Нанаймо",
"new-westminster"=>"Нью Вестмінстер",
"prince-george"=>"Принс Джордж",
"richmond"=>"Річмонд",
"surrey"=>"Суррей",
"vancouver"=>"Ванкувер",
"victoria"=>"Вікторія",
"white-rock"=>"Вайт-Рок",
"okanagan"=>"Келоуна",
"ladner"=>"Ладнер",
 ], 
 '6065171' => [
 "winnipeg"=>"Вінніпег",
 ], 
 '6087430' => [
 "fredericton"=>"Фредеріктон",
"moncton"=>"Монктон",
"saint-john"=>"Сент Джон",
 ], 
 '6091530' => [
 "dartmouth"=>"Дартмут",
"halifax"=>"Галіфакс",
"sydney"=>"Сідней",
 ], 
 '6093943' => [
 "ajax"=>"Ейджакс",
"barrie"=>"Баррі",
"brampton"=>"Брамптон",
"brantford"=>"Брантфорд",
"burlington"=>"Берлінгтон",
"cambridge"=>"Кеймбрідж",
"etobicoke"=>"Етобіко",
"greater-sudbury"=>"Грейтер Садбері",
"guelph"=>"Гвелф",
"hamilton"=>"Гамільтон",
"kingston"=>"Кінгстон",
"kitchener"=>"Кітченер",
"london"=>"Лондон",
"markham"=>"Маркем",
"milton"=>"Мілтон",
"mississauga"=>"Місісауга",
"newmarket"=>"Ньюмаркет",
"niagara-falls"=>"Ніагара Фолс",
"norfolk-county"=>"Норфолк",
"north-bay"=>"Норт Бей",
"north-york"=>"Норт Йорк",
"oakville"=>"Оквілл",
"oshawa"=>"Ошава",
"ottawa"=>"Оттава",
"peterborough"=>"Пітерборо",
"pickering"=>"Пікерінг",
"richmond-hill"=>"Річмонд Хілл",
"sarnia"=>"Сарнія",
"sault-ste-marie"=>"Су-Сент-Марі",
"st-catharines"=>"Сент Катарінс",
"thunder-bay"=>"Тандер Бей",
"toronto"=>"Торонто",
"vaughan"=>"Вон",
"waterloo"=>"Ватерлоо",
"welland"=>"Велланд",
"windsor"=>"Віндзор",
"scarborough"=>"Скарборо",
"willowdale"=>"Вілловдале",
 ], 
 '6115047' => [
 "brossard"=>"Бросар",
"drummondville"=>"Дрюмонвілл",
"gatineau"=>"Гатине",
"granby"=>"Гранбі",
"laval"=>"Лаваль",
"longueuil"=>"Лонгуей",
"montréal"=>"Монреаль",
"repentigny"=>"Репантінья",
"saguenay"=>"Сагеней",
"saint-hyacinthe"=>"Сент-Іасент",
"saint-jean-sur-richelieu"=>"Сен-Жан-сюр-Рішельє",
"saint-jérôme"=>"Сен Жером",
"saint-laurent"=>"Сен Лоран",
"saint-léonard"=>"Сен Леонар",
"sherbrooke"=>"Шербрук",
"terrebonne"=>"Тербон",
"trois-rivières"=>"Труа-Рівьєр",
"québec"=>"Квебек",
"lévis"=>"Леві",
"jonquière"=>"Жонкьєр",
 ], 
 '6141242' => [
 "regina"=>"Реджайна",
"saskatoon"=>"Саскатун",
 ], 
 '6354959' => [
 "st-johns"=>"Сент Джонс",
 ], 
];