<?php 

  return [
  '2513413' => [
 "murcia"=>"Мурсія",
"molina-de-segura"=>"Моліна-де-Сегура",
"lorca"=>"Лорка",
"cartagena"=>"Картахена",
 ], 
 '2519582' => [
 "ceuta"=>"Сеута",
 ], 
 '2521383' => [
 "palma"=>"Пальма",
"calvià"=>"Кальвія",
 ], 
 '2593109' => [
 "vélez-málaga"=>"Велес-Малага",
"utrera"=>"Утрера",
"torremolinos"=>"Торремолінос",
"sevilla"=>"Севілья",
"sanlúcar-de-barrameda"=>"Санлукар-де-Баррамеда",
"san-fernando"=>"Сан-Фернандо",
"roquetas-de-mar"=>"Рокетас-де-Мар",
"motril"=>"Мотріль",
"mijas"=>"Михас",
"marbella"=>"Марбелья",
"málaga"=>"Малага",
"linares"=>"Линарес",
"la-línea-de-la-concepción"=>"Ла-Лінеа-де-ла-Консепсьон",
"jerez-de-la-frontera"=>"Херес-де-ла-Фронтера",
"jaén"=>"Хаен",
"huelva"=>"Уельва",
"granada"=>"Гранада",
"fuengirola"=>"Фуенхіролу",
"estepona"=>"Естепона",
"el-puerto-de-santa-maría"=>"Ель-Пуерто-де-Санта-Марія",
"el-ejido"=>"Ель-Ехідо",
"dos-hermanas"=>"Дос-Ерманас",
"córdoba"=>"Кордоба",
"chiclana-de-la-frontera"=>"Чиклана-де-ла-Фронтера",
"campiña"=>"Сільська місцевість",
"cadiz"=>"Кадіс",
"benalmádena"=>"Бенальмадена",
"almería"=>"Альмерія",
"algeciras"=>"Альхесірас",
"alcalá-de-guadaira"=>"Алькала-де-Гуадаїра",
 ], 
 '2593110' => [
 "telde"=>"Тельде",
"santa-lucía"=>"Санта Люсія",
"santa-cruz-de-tenerife"=>"Санта-Крус-де-Тенеріфе",
"la-laguna"=>"Ла-Лагуна",
"san-bartolomé-de-tirajana"=>"Сан-Бартоломе-де-Тірахана",
"las-palmas-de-gran-canaria"=>"Лас-Пальмас-де-Гран-Канарія",
"arrecife"=>"Арресіфе",
"arona"=>"Арона",
 ], 
 '2593111' => [
 "toledo"=>"Толедо",
"talavera-de-la-reina"=>"Талавера-де-ла-Рейна",
"puertollano"=>"Пуертольяно",
"ciudad-real"=>"Сьюдад-Лайнер",
"albacete"=>"Альбасете",
"guadalajara"=>"Гвадалахара",
"cuenca"=>"Куєнка",
 ], 
 '2593112' => [
 "mérida"=>"Меріда",
"cáceres"=>"Касерес",
"badajoz"=>"Бадахос",
 ], 
 '2593113' => [
 "vila-real"=>"Вільярреаль",
"valencia"=>"Валенсія",
"torrevieja"=>"Торревьєха",
"torrent"=>"Торренте",
"san-vicent-del-raspeig"=>"Сан-Вісенте-дель-Распеч",
"sagunto"=>"Сагунто",
"paterna"=>"Патерна",
"orihuela"=>"Оріуела",
"gandia"=>"Гандія",
"elda"=>"Ельда",
"elche"=>"Ельче",
"castelló-de-la-plana"=>"Кастельйон-де-ла-Плана",
"benidorm"=>"Бенідорм",
"alicante"=>"Аліканте",
"alcoy"=>"Алькой",
"groa-de-murviedro"=>"Гроа-де-Мурвієдре",
 ], 
 '3114710' => [
 "oviedo"=>"Овьєдо",
"gijón"=>"Хіхон",
"avilés"=>"Авілес",
 ], 
 '3115609' => [
 "pamplona"=>"Памплона",
 ], 
 '3117732' => [
 "villaverde"=>"Вільяверде",
"vicálvaro"=>"Вікальваро",
"valdemoro"=>"Вальдеморо",
"rivas-vaciamadrid"=>"Рівас-Васіамадрид",
"torrejón-de-ardoz"=>"Торрехон-де-Ардос",
"tetuán-de-las-victorias"=>"Тетуан-де-лас-вікторіас",
"san-sebastián-de-los-reyes"=>"Сан-Себастьян-де-лос-Рейєс",
"puente-de-vallecas"=>"Пуенте-де-Вальєкас",
"pozuelo-de-alarcón"=>"Посуело де Аларкон",
"parla"=>"Парла",
"móstoles"=>"Мостолес",
"moratalaz"=>"Мораталаз",
"majadahonda"=>"Махадаонда",
"madrid"=>"Мадрид",
"leganés"=>"Леганес",
"las-rozas-de-madrid"=>"Лас-Росас-де-Мадрид",
"hortaleza"=>"Орталеза",
"getafe"=>"Хетафе",
"fuenlabrada"=>"Фуенлабрада",
"coslada"=>"Кослада",
"collado-villalba"=>"Кольядо-Вільяльба",
"ciudad-lineal"=>"Сьюдад-Реаль",
"chamartín"=>"Чамартін",
"arganda"=>"Арганда",
"aranjuez"=>"Аранхуес",
"alcorcón"=>"Алькоркон",
"alcobendas"=>"Алькобендас",
"alcalá-de-henares"=>"Алькала-де-Енарес",
"moncloa-aravaca"=>"Монклоа-Аравак",
"arganzuela"=>"Аргансуела",
"san-blas"=>"Сан-Блас",
"latina"=>"Латина",
"usera"=>"Юсера",
"salamanca"=>"Саламанка",
"chamberí"=>"Чембери",
"carabanchel"=>"Карабанчель",
"city-center"=>"Сити Центр",
"retiro"=>"Ретіро",
"fuencarral-el-pardo"=>"Фуенкорал-Ель-Пардо",
"villa-de-vallecas"=>"Вілья-де-Вальєкас",
 ], 
 '3336897' => [
 "logroño"=>"Логроньо",
 ], 
 '3336898' => [
 "torrelavega"=>"Торрелавега",
"santander"=>"Сантандер",
 ], 
 '3336899' => [
 "zaragoza"=>"Сарагоса",
"huesca"=>"Уеска",
"delicias"=>"Деліціяс",
 ], 
 '3336900' => [
 "zamora"=>"Замора",
"valladolid"=>"Вальядолід",
"segovia"=>"Сеговія",
"salamanca"=>"Salamanca",
"ponferrada"=>"Понферрада",
"palencia"=>"Паленсія",
"león"=>"Леон",
"burgos"=>"Бургос",
"ávila"=>"Авіла",
 ], 
 '3336901' => [
 "vilanova-i-la-geltrú"=>"Вільянуева та Ла Гелтру",
"viladecans"=>"Віладеканс",
"terrassa"=>"Тераса",
"tarragona"=>"Таррагона",
"cerdanyola-del-vallès"=>"Серданьола-дель-Вальєс",
"santa-coloma-de-gramenet"=>"Санта-Колома-де-Граменет",
"sant-cugat-del-vallès"=>"Сан-Кугат-дель-Вальєс",
"sant-boi-de-llobregat"=>"Сан-Бой-де-Льобрегат",
"sant-andreu-de-palomar"=>"Сан-Андреу-де-Паломар",
"sabadell"=>"Сабадель",
"rubí"=>"Рубі",
"reus"=>"Реус",
"mollet-del-vallès"=>"Мольєт-дель-Вальєс",
"mataró"=>"Матаро",
"manresa"=>"Манреса",
"lleida"=>"Льєйда",
"lhospitalet-de-llobregat"=>"Оспіталет-де-Льобрегат",
"granollers"=>"Гранольєрс",
"gràcia"=>"Грасіа",
"girona"=>"Жирона",
"el-prat-de-llobregat"=>"Ель-Прат-де-Льобрегат",
"cornellà-de-llobregat"=>"Корнелья-де-Льобрегат",
"castelldefels"=>"Кастельдефельс",
"barcelona"=>"Барселона",
"badalona"=>"Бадалона",
"nou-barris"=>"Ноу-Барис",
"eixample"=>"Ешампле",
"les-corts"=>"Лес Кортс",
"sarrià-sant-gervasi"=>"Саррія-Сант-Жервасі",
"horta-guinardó"=>"Орта-Гинардо",
"sants-montjuïc"=>"Сантс-Монтжуїк",
"sant-martí"=>"Сан-Марті",
"ciutat-vella"=>"Ciutat Vella",
 ], 
 '3336902' => [
 "vigo"=>"Віго",
"santiago-de-compostela"=>"Сантьяго-де-Компостела",
"pontevedra"=>"Понтеведра",
"ourense"=>"Оренсе",
"lugo"=>"Луго",
"a-coruña"=>"Ла-Корунья",
"ferrol"=>"Ферроль",
 ], 
 '3336903' => [
 "barakaldo"=>"Баракальдо",
"irun"=>"Ирун",
"getxo"=>"Гечо",
"bilbao"=>"Більбао",
"algorta"=>"Альгорта",
"santutxu"=>"Сантуксу",
"donostia--san-sebastián"=>"Сан-Себастьян",
"gasteiz--vitoria"=>"Віторія-Гастейс",
 ], 
 '6362988' => [
 "melilla"=>"Мелілья",
 ], 
];