<?php 

  return [
  '2985244' => [
 "toulon"=>"Тулон",
"nice"=>"Ніцца",
"marseille"=>"Марсель",
"la-seyne-sur-mer"=>"Ла-Сен-сюр-Мер",
"hyères"=>"Єр",
"fréjus"=>"Фрежус",
"cannes"=>"Канни",
"avignon"=>"Авіньйон",
"arles"=>"Арль",
"antibes"=>"Антіб",
"aix-en-provence"=>"Екс-ан-Прованс",
"marseille-08"=>"Марсель 08",
"marseille-10"=>"Марсель 10",
"marseille-09"=>"Марсель 09",
"marseille-11"=>"Марсель 11",
"marseille-12"=>"Марсель 12",
"marseille-13"=>"Марсель 13",
"marseille-14"=>"Марсель 14",
"marseille-15"=>"Марсель 15",
 ], 
 '2988289' => [
 "saint-nazaire"=>"Сен-Назер",
"nantes"=>"Нант",
"le-mans"=>"Ле-Ман",
"laval"=>"Лаваль",
"la-roche-sur-yon"=>"Ла-Рош-сюр-Іон",
"cholet"=>"Шоле",
"angers"=>"Анже",
 ], 
 '3012874' => [
 "vitry-sur-seine"=>"Вітрі-сюр-Сен",
"versailles"=>"Версаль",
"sartrouville"=>"Сартрувіль",
"sarcelles"=>"Сарсель",
"saint-maur-des-fossés"=>"Сен-Мор-де-Фоссе",
"saint-denis"=>"Сен-Дені",
"rueil-malmaison"=>"Рюэй-Мальмезон",
"paris"=>"Париж",
"pantin"=>"Пантен",
"noisy-le-grand"=>"Нуазі-ле-Гран",
"neuilly-sur-seine"=>"Нейї-сюр-Сен",
"nanterre"=>"Нантер",
"montreuil"=>"Монтрей",
"meaux"=>"Мо",
"maisons-alfort"=>"Мезон-Альфор",
"levallois-perret"=>"Леваллуа-Перре",
"ivry-sur-seine"=>"Іврі-сюр-Сен",
"issy-les-moulineaux"=>"Іссі-Ле-Муліно",
"fontenay-sous-bois"=>"Фонтене-су-Буа",
"évry"=>"Еврі",
"drancy"=>"Дранси",
"créteil"=>"Кретей",
"courbevoie"=>"Курбевуа",
"colombes"=>"Коломб",
"clichy"=>"Кліші",
"clamart"=>"Кламар",
"champigny-sur-marne"=>"Шампіньї-Сюр-Марн",
"cergy"=>"Сержі",
"boulogne-billancourt"=>"Булонь-Біянкур",
"aulnay-sous-bois"=>"Оне-су-Буа",
"aubervilliers"=>"Обервільє",
"asnières-sur-seine"=>"Аньєр-сюр-Сен",
"argenteuil"=>"Аржантей",
"antony"=>"Антоні",
"saint-quentin-en-yvelines"=>"Сен-Кантен-ан-Івелін",
"cergy-pontoise"=>"Сержі-Понтуаз",
 ], 
 '3023519' => [
 "ajaccio"=>"Аяччо",
 ], 
 '3027939' => [
 "tours"=>"Тур",
"orléans"=>"Орлеан",
"châteauroux"=>"Шатору",
"bourges"=>"Бурж",
"blois"=>"Блуа",
 ], 
 '3030293' => [
 "vannes"=>"Ванн",
"saint-malo"=>"Сен-Мало",
"saint-brieuc"=>"Сен-Бріє",
"rennes"=>"Ренн",
"quimper"=>"Кемпер",
"lorient"=>"Лорьян",
"brest"=>"Брест",
 ], 
 '11071619' => [
 "dijon"=>"Діжон",
"besançon"=>"Безансон",
"belfort"=>"Бельфор",
 ], 
 '11071620' => [
 "poitiers"=>"Пуатьє",
"pessac"=>"Песак",
"pau"=>"По",
"niort"=>"Ньор",
"mérignac"=>"Меріньяк",
"limoges"=>"Лімож",
"la-rochelle"=>"Ла-Рошель",
"brive-la-gaillarde"=>"Брив-ла-Гаярд",
"bordeaux"=>"Бордо",
 ], 
 '11071621' => [
 "rouen"=>"Руан",
"le-havre"=>"Гавр",
"évreux"=>"Евре",
"caen"=>"Кан",
 ], 
 '11071622' => [
 "troyes"=>"Труа",
"strasbourg"=>"Страсбург",
"reims"=>"Реймс",
"nancy"=>"Нансі",
"mulhouse"=>"Мюлуз",
"metz"=>"Мец",
"colmar"=>"Кольмар",
"charleville-mézières"=>"Шарлевіль-Мезьєр",
"châlons-en-champagne"=>"Шалон-ан-Шампань",
 ], 
 '11071623' => [
 "toulouse"=>"Тулуза",
"tarbes"=>"Тарб",
"perpignan"=>"Перпіньян",
"nîmes"=>"Нім",
"narbonne"=>"Нарбонн",
"montpellier"=>"Монпельє",
"montauban"=>"Монтобан",
"béziers"=>"Безье",
"albi"=>"Альбі",
 ], 
 '11071624' => [
 "tourcoing"=>"Туркуен",
"saint-quentin"=>"Сен-Кантен",
"roubaix"=>"Рубе",
"lille"=>"Лілль",
"dunkerque"=>"Дюнкерк",
"calais"=>"Кале",
"beauvais"=>"Бове",
"amiens"=>"Амьєн",
"villeneuve-dascq"=>"Вільнев-д\\\'Аск",
 ], 
 '11071625' => [
 "villeurbanne"=>"Війєрбан",
"vénissieux"=>"Венісьє",
"valence"=>"Валанс",
"saint-étienne"=>"Сент-Етьєн",
"lyon"=>"Ліон",
"grenoble"=>"Гренобль",
"clermont-ferrand"=>"Клермон-Ферран",
"chambéry"=>"Шамбері",
 ], 
];