<?php 

  return [
  '2523119' => [
 "vittoria"=>"Вітторія",
"trapani"=>"Трапані",
"siracusa"=>"Сіракузи",
"ragusa"=>"Рагуза",
"palermo"=>"Палермо",
"messina"=>"Мессіна",
"marsala"=>"Марсала",
"gela"=>"Джела",
"catania"=>"Катанія",
"caltanissetta"=>"Кальтанісетта",
"bagheria"=>"Багерія",
 ], 
 '2523228' => [
 "quartu-santelena"=>"Куарту-Сант-Елена",
"cagliari"=>"Кальярі",
"sassari"=>"Сассарі",
 ], 
 '2525468' => [
 "reggio-calabria"=>"Реджо-Калабрія",
"nicastro-sambiase"=>"Нікастро-Самбіаз",
"cosenza"=>"Козенца",
"catanzaro"=>"Катанзаро",
"lamezia-terme"=>"Ламеція-Терме",
 ], 
 '3164604' => [
 "vicenza"=>"Виченца",
"verona"=>"Верона",
"venice"=>"Венеція",
"treviso"=>"Тревізо",
"padova"=>"Падуя",
"mestre"=>"Местре",
 ], 
 '3165048' => [
 "terni"=>"Терні",
"perugia"=>"Перуджа",
 ], 
 '3165244' => [
 "trento"=>"Тренто",
"bolzano"=>"Больцано",
 ], 
 '3165361' => [
 "prato"=>"Прато",
"pistoia"=>"Пістоя",
"pisa"=>"Піза",
"massa"=>"Масса",
"lucca"=>"Лукка",
"livorno"=>"Ліворно",
"grosseto"=>"Гроссето",
"florence"=>"Флоренція",
"carrara"=>"Каррара",
"arezzo"=>"Ареццо",
 ], 
 '3169778' => [
 "trani"=>"Трані",
"taranto"=>"Таранто",
"san-severo"=>"Сан-Северо",
"molfetta"=>"Мольфетта",
"manfredonia"=>"Манфредонія",
"lecce"=>"Лечче",
"foggia"=>"Фоджа",
"cerignola"=>"Черіньйол",
"brindisi"=>"Бріндізі",
"bitonto"=>"Бітонто",
"bisceglie"=>"Бішельє",
"barletta"=>"Барлетта",
"bari"=>"Барі",
"andria"=>"Андрія",
"altamura"=>"Альтамура",
 ], 
 '3170831' => [
 "turin"=>"Турін",
"novara"=>"Новара",
"asti"=>"Асті",
"alessandria"=>"Олесандрія",
 ], 
 '3174004' => [
 "pesaro"=>"Пезаро",
"ancona"=>"Анкона",
 ], 
 '3174618' => [
 "vigevano"=>"Віджевано",
"varese"=>"Варесе",
"sesto-san-giovanni"=>"Сесто-Сан-Джованні",
"pavia"=>"Павія",
"monza"=>"Монца",
"milano"=>"Мілан",
"legnano"=>"Леньяно",
"gallarate"=>"Галларате",
"cremona"=>"Кремона",
"como"=>"Комо",
"cinisello-balsamo"=>"Чинізелло-Бальсамо",
"busto-arsizio"=>"Бусто-Арсіціо",
"brescia"=>"Брешіа",
"bergamo"=>"Бергамо",
 ], 
 '3174725' => [
 "savona"=>"Савона",
"la-spezia"=>"Спеція",
"genoa"=>"Генуя",
 ], 
 '3174976' => [
 "rome"=>"Рим",
"lido-di-ostia"=>"Лідо-ді-Остія",
"latina"=>"Латина",
"acilia-castel-fusano-ostia-antica"=>"Ацилия-Кастель Фузано-Остия Антика",
"guidonia-montecelio"=>"Гуїдонія-Монтечельйо",
 ], 
 '3176525' => [
 "udine"=>"Удіне",
"trieste"=>"Трієст",
 ], 
 '3177401' => [
 "rimini"=>"Ріміні",
"reggio-nellemilia"=>"Реджо-нель-Емілія",
"ravenna"=>"Равенна",
"piacenza"=>"Пьяченця",
"parma"=>"Парма",
"modena"=>"Модена",
"imola"=>"Імола",
"forlì"=>"Форлі",
"ferrara"=>"Феррара",
"cesena"=>"Чезена",
"carpi-centro"=>"Карпі",
"bologna"=>"Болонья",
 ], 
 '3181042' => [
 "torre-del-greco"=>"Торре-дель-Греко",
"salerno"=>"Салерно",
"portici"=>"Портічі",
"napoli"=>"Неаполь",
"giugliano-in-campania"=>"Джульяно-ін-Кампанья",
"ercolano"=>"Ерколано",
"castellammare-di-stabia"=>"Кастелламмаре-ді-Стабія",
"casoria"=>"Казорія",
"caserta"=>"Казерта",
"aversa"=>"Аверса",
"afragola"=>"Афрагола",
"acerra"=>"Ачерра",
 ], 
 '3182306' => [
 "potenza"=>"Потенца",
"matera"=>"Матера",
 ], 
 '3183560' => [
 "pescara"=>"Пескара",
 ], 
];