<?php 

  return [
  '2743698' => [
 "zoetermeer"=>"Зутермер",
"vlaardingen"=>"Влардінген",
"spijkenisse"=>"Спейкеніссе",
"the-hague"=>"Гаага",
"schiedam"=>"Схiдам",
"rotterdam"=>"Роттердам",
"leiden"=>"Лейден",
"gouda"=>"Гауда",
"dordrecht"=>"Дордрехт",
"delft"=>"Делфт",
"delfshaven"=>"Дельфсхавен",
"capelle-aan-den-ijssel"=>"Капелі ан ден Ейссел",
"alphen-aan-den-rijn"=>"Алфен-ан-де-Рейн",
 ], 
 '2745909' => [
 "zeist"=>"Зейст",
"veenendaal"=>"Венендал",
"utrecht"=>"Утрехт",
"nieuwegein"=>"Ньивегейн",
"amersfoort"=>"Амерсфорт",
 ], 
 '2748838' => [
 "zwolle"=>"Зволле",
"hengelo"=>"Хенгело",
"hardenberg"=>"Харденберг",
"enschede"=>"Енсхеде",
"deventer"=>"Девентер",
"almelo"=>"Алмело",
 ], 
 '2749879' => [
 "zaanstad"=>"Занстад",
"zaandam"=>"Зандам",
"velsen-zuid"=>"Велсен-Зейд",
"purmerend"=>"Пюрмеренд",
"hoorn"=>"Хорн",
"hoofddorp"=>"Хофддорп",
"hilversum"=>"Хілверсюм",
"haarlem"=>"Харлем",
"den-helder"=>"Ден-Хелдер",
"amsterdam"=>"Амстердам",
"amstelveen"=>"Амстелвен",
"alkmaar"=>"Алкмар",
"amsterdam-zuidoost"=>"Амстердам-Зюйдост",
 ], 
 '2749990' => [
 "tilburg"=>"Тілбург",
"s-hertogenbosch"=>"Гертогенбос",
"roosendaal"=>"Розендал",
"oss"=>"Осс",
"oosterhout"=>"Остерхаут",
"helmond"=>"Хелмонд",
"eindhoven"=>"Ейндховен",
"breda"=>"Бреда",
"bergen-op-zoom"=>"Берген-оп-Зом",
 ], 
 '2751596' => [
 "venlo"=>"Венло",
"maastricht"=>"Маастріхт",
"heerlen"=>"Херлен",
"born"=>"Борн",
 ], 
 '2755249' => [
 "groningen"=>"Гронінген",
 ], 
 '2755634' => [
 "nijmegen"=>"Наймеген",
"ede"=>"Еде",
"arnhem"=>"Арнем",
"apeldoorn"=>"Апелдорн",
 ], 
 '2755812' => [
 "leeuwarden"=>"Леуварден",
 ], 
 '2756631' => [
 "emmen"=>"Еммен",
"assen"=>"Ассен",
 ], 
 '3319179' => [
 "lelystad"=>"Лелістад",
"almere-stad"=>"Алмере-Стад",
 ], 
];