<?php

  return [
      "zurich"=>"Цюрих",
      "train"=>"Цуг",
      "vaud"=>"Во",
      "valais"=>"Вале",
      "uri"=>"Ури",
      "ticino"=>"Тичино",
      "thurgau"=>"Тургау",
      "solothurn"=>"Золотурн",
      "schwyz"=>"Швиц",
      "schaffhausen"=>"Шаффхаузен",
      "saint_gallen"=>"Санкт-Галлен",
      "obwalden"=>"Обвальден",
      "nidwalden"=>"Нидвальден",
      "neuchâtel"=>"Невшатель",
      "lucerne"=>"Люцерна",
      "jura"=>"Юра",
      "grisons"=>"Гризоны",
      "glarus"=>"Гларус",
      "geneva"=>"Женева",
      "fribourg"=>"Фрибург",
      "bern"=>"Берн",
      "basel_city"=>"Базель Сити",
      "basel-landschaft"=>"Базельский пейзаж",
      "appenzell_ausserrhoden"=>"Аппенцелль Ауссерроден",
      "appenzell_innerrhoden"=>"Аппенцелль Иннерроден",
      "aargau"=>"Ааргау",
];
