<?php

  return [
      "bjelovarsko-bilogorska"=>"Беловар-Билогора",
      "brodsko-posavska"=>"Бродско-Посавская",
      "dubrovačko-neretvanska"=>"Дубровачка-Неретванска",
      "istarska"=>"Жупания Истрия",
      "karlovačka"=>"Карловачка",
      "koprivničko-križevačka"=>"Копривничко-Крижевачка",
      "krapinsko-zagorska"=>"Крапинско-Загорская",
      "ličko-senjska"=>"Личко-Сеньска",
      "međimurska"=>"Меджимурска",
      "osječko-baranjska"=>"Осиецко-Бараньская",
      "požeško-slavonska"=>"Пожежско-Славонская",
      "primorsko-goranska"=>"Приморско-горанска",
      "šibensko-kninska"=>"Шибеник-Книн",
      "sisačko-moslavačka"=>"Сисацко-Мославинская",
      "splitsko-dalmatinska"=>"Сплитско-Далматинска",
      "varaždinska"=>"Вараждинска",
      "vukovarsko-srijemska"=>"Вуковарско-Сриемска",
      "zadarska"=>"Задарска",
      "zagrebačka"=>"Загребачка",
      "grad_zagreb"=>"Загреб",
      "virovitičko-podravska"=>"Вировитицко-Подравская",
];
