<?php

  return [
      "edinet" => "Единцы",
      "ungheni" => "Унгень",
      "teleneşti" => "Теленешти",
      "taraclia" => "Тараклия",
      "ştefan-vodă" => "Штефан-Водский",
      "strășeni" => "Страшены",
      "soroca" => "Сороки",
      "rîşcani" => "Рышкани",
      "rezina" => "Резина",
      "orhei" => "Оргей",
      "ocniţa" => "Окница",
      "anenii_noi" => "Новые Анены",
      "nisporeni" => "Ниспорены",
      "leova" => "Леова",
      "sîngerei" => "Сынжерея",
      "criuleni" => "Криулены",
      "laloveni" => "Яловены",
      "chişinău" => "Кишинёв",
      "căuşeni" => "Каушаны",
      "cantemir" => "Кантемир",
      "cahul" => "Кагул",
      "glodeni" => "Глодени",
      "floresti" => "Флорешты",
      "făleşti" => "Фэлешть",
      "dubăsari" => "Дубоссары",
      "drochia" => "Дрокия",
      "donduşeni" => "Дондюшаны",
      "cimişlia" => "Чимишлия",
      "briceni" => "Бричени",
      "basarabeasca" => "Бессарабка",
      "hînceşti" => "Хынчешты",
      "şoldăneşti" => "Шолданештский район",
      "stînga_nistrului" => "Преднестровье",
      "găgăuzia" => "Гагаузия",
      "bender" => "Бендеры",
      "bălţi" => "Бельцы",
];
