<?php

  return [
      "vrancea" => "Вранча",
      "vâlcea" => "Вылча",
      "vaslui" => "Васлуй",
      "tulcea" => "Тулча",
      "timiş" => "Тимиш",
      "teleorman" => "Телеорман",
      "suceava" => "Сучава",
      "sibiu" => "Сибиу",
      "satu_mare" => "Сату Маре",
      "sălaj" => "Сэладж",
      "prahova" => "Прахова",
      "olt" => "Олт",
      "neamţ" => "Неамц",
      "mureş" => "Муреш",
      "mehedinţi" => "Мехединцы",
      "maramureş" => "Марамуреш",
      "iasi" => "Яссы",
      "ialomiţa" => "Яломица",
      "hunedoara" => "Хунедоара",
      "harghita" => "Харгита",
      "gorj" => "Горж",
      "giurgiu" => "Джурджу",
      "galaţi" => "Галац",
      "dolj" => "Долж",
      "dâmboviţa" => "Дымбовица",
      "covasna" => "Ковасна",
      "constanța" => "Констанца",
      "cluj" => "Клуж",
      "caraş-severin" => "Караш-Северин",
      "călăraşi" => "Кэлэраши",
      "buzău" => "Бузэу",
      "bucuresti" => "Бухарест",
      "braşov" => "Брашов",
      "brăila" => "Брэила",
      "botoşani" => "Ботошани",
      "bistriţa-năsăud" => "Бистрица-Нэсэуд",
      "bihor" => "Бихор",
      "bacău" => "Бакау",
      "argeş" => "Аргеш",
      "arad" => "Арад",
      "alba" => "Альба",
      "ilfov" => "Ильфов",
];
