<?php 

  return [
  '5883102' => [
 "calgary"=>"Калгари",
"edmonton"=>"Эдмонтон",
"fort-mcmurray"=>"Форт-МакМеррей",
"lethbridge"=>"Летбридж",
"medicine-hat"=>"Медисин Хат",
"red-deer"=>"Ред Дир",
"sherwood-park"=>"Шервуд Парк",
"st-albert"=>"Сент-Альберт",
 ], 
 '5909050' => [
 "abbotsford"=>"Абботсфорд",
"anmore"=>"Канмор",
"burnaby"=>"Бернаби",
"chilliwack"=>"Чилливак",
"coquitlam"=>"Кокуитлам",
"delta"=>"Делта",
"kamloops"=>"Камлупс",
"kelowna"=>"Келоуна",
"langley"=>"Лэнгли",
"maple-ridge"=>"Мейпл Ридж",
"nanaimo"=>"Нанаймо",
"new-westminster"=>"Нью Уэстминстер",
"prince-george"=>"Принс Джордж",
"richmond"=>"Ричмонд",
"surrey"=>"Суррей",
"vancouver"=>"Ванкувер",
"victoria"=>"Виктория",
"white-rock"=>"Уайт Рок",
"okanagan"=>"Келоуна",
"ladner"=>"Ладнер",
 ], 
 '6065171' => [
 "winnipeg"=>"Виннипег",
 ], 
 '6087430' => [
 "fredericton"=>"Фредериктон",
"moncton"=>"Монктон",
"saint-john"=>"Сент Джон",
 ], 
 '6091530' => [
 "dartmouth"=>"Дартмут",
"halifax"=>"Галифакс",
"sydney"=>"Сидней",
 ], 
 '6093943' => [
 "ajax"=>"Эйджакс",
"barrie"=>"Барри",
"brampton"=>"Брамптон",
"brantford"=>"Брантфорд",
"burlington"=>"Берлингтон",
"cambridge"=>"Кеймбридж",
"etobicoke"=>"Этобико",
"greater-sudbury"=>"Грейтер Садбери",
"guelph"=>"Гвелф",
"hamilton"=>"Гамильтон",
"kingston"=>"Кингстон",
"kitchener"=>"Китченер",
"london"=>"Лондон",
"markham"=>"Маркем",
"milton"=>"Милтон",
"mississauga"=>"Миссисауга",
"newmarket"=>"Ньюмаркет",
"niagara-falls"=>"Ниагара Фолс",
"norfolk-county"=>"Норфолк",
"north-bay"=>"Норт Бей",
"north-york"=>"Норт Йорк",
"oakville"=>"Оквилл",
"oshawa"=>"Ошава",
"ottawa"=>"Оттава",
"peterborough"=>"Питерборо",
"pickering"=>"Пикеринг",
"richmond-hill"=>"Ричмонд Хилл",
"sarnia"=>"Сарния",
"sault-ste-marie"=>"Су-Сент-Мари",
"st-catharines"=>"Сент-Катаринс",
"thunder-bay"=>"Тандер Бей",
"toronto"=>"Торонто",
"vaughan"=>"Вон",
"waterloo"=>"Ватерлоо",
"welland"=>"Велланд",
"windsor"=>"Виндзор",
"scarborough"=>"Скарборо",
"willowdale"=>"Вилловдале",
 ], 
 '6115047' => [
 "brossard"=>"Броссар",
"drummondville"=>"Дрюммонвилль",
"gatineau"=>"Гатино",
"granby"=>"Гранби",
"laval"=>"Лаваль",
"longueuil"=>"Лонгёй",
"montréal"=>"Монреаль",
"repentigny"=>"Репантиньи",
"saguenay"=>"Сагеней",
"saint-hyacinthe"=>"Сент-Иасент",
"saint-jean-sur-richelieu"=>"Сен-Жан-сюр-Ришелье",
"saint-jérôme"=>"Сен-Жером",
"saint-laurent"=>"Сен-Лоран",
"saint-léonard"=>"Сейнт Леонард",
"sherbrooke"=>"Шербрук",
"terrebonne"=>"Тербон",
"trois-rivières"=>"Труа-Ривьер",
"québec"=>"Квебек",
"lévis"=>"Леви",
"jonquière"=>"Жонкьер",
 ], 
 '6141242' => [
 "regina"=>"Реджайна",
"saskatoon"=>"Саскатун",
 ], 
 '6354959' => [
 "st-johns"=>"Сент-Джонс",
 ], 
];