<?php 

  return [
  '2513413' => [
 "murcia"=>"Мурсия",
"molina-de-segura"=>"Молина де Сегура",
"lorca"=>"Лорка",
"cartagena"=>"Картахена",
 ], 
 '2519582' => [
 "ceuta"=>"Сеута",
 ], 
 '2521383' => [
 "palma"=>"Пальма",
"calvià"=>"Кальвия",
 ], 
 '2593109' => [
 "vélez-málaga"=>"Велес-Малага",
"utrera"=>"Утрера",
"torremolinos"=>"Торремолинос",
"sevilla"=>"Севилья",
"sanlúcar-de-barrameda"=>"Санлукар-де-Баррамеда",
"san-fernando"=>"Сан-Фернандо",
"roquetas-de-mar"=>"Рокетас-де-Мар",
"motril"=>"Мотриль",
"mijas"=>"Михас",
"marbella"=>"Марбелья",
"málaga"=>"Малага",
"linares"=>"Линарес",
"la-línea-de-la-concepción"=>"Ла-Линеа-де-ла-Консепсьон",
"jerez-de-la-frontera"=>"Херес-де-ла-Фронтера",
"jaén"=>"Хаэн",
"huelva"=>"Уэльва",
"granada"=>"Гранада",
"fuengirola"=>"Фуэнхирола",
"estepona"=>"Эстепона",
"el-puerto-de-santa-maría"=>"Эль-Пуэрто-де-Санта-Мария",
"el-ejido"=>"Эль-Эхидо",
"dos-hermanas"=>"Дос-Эрманас",
"córdoba"=>"Кордоба",
"chiclana-de-la-frontera"=>"Чиклана-де-ла-Фронтера",
"campiña"=>"Сельская местность",
"cadiz"=>"Кадис",
"benalmádena"=>"Бенальмадена",
"almería"=>"Альмерия",
"algeciras"=>"Альхесирас",
"alcalá-de-guadaira"=>"Алькала-де-Гуадаира",
 ], 
 '2593110' => [
 "telde"=>"Тельде",
"santa-lucía"=>"Санта-Лусия",
"santa-cruz-de-tenerife"=>"Санта-Крус-де-Тенерифе",
"la-laguna"=>"Ла-Лагуна",
"san-bartolomé-de-tirajana"=>"Сан-Бартоломе-де-Тирахана",
"las-palmas-de-gran-canaria"=>"Лас-Пальмас-де-Гран-Канария",
"arrecife"=>"Арресифе",
"arona"=>"Арона",
 ], 
 '2593111' => [
 "toledo"=>"Толедо",
"talavera-de-la-reina"=>"Талавера-де-ла-Рейна",
"puertollano"=>"Пуэртольяно",
"ciudad-real"=>"Сьюдад-Реаль",
"albacete"=>"Альбасете",
"guadalajara"=>"Гвадалахара",
"cuenca"=>"Куэнка",
 ], 
 '2593112' => [
 "mérida"=>"Мерида",
"cáceres"=>"Касерес",
"badajoz"=>"Бадахос",
 ], 
 '2593113' => [
 "vila-real"=>"Вильярреаль",
"valencia"=>"Валенсия",
"torrevieja"=>"Торревьеха",
"torrent"=>"Торренте",
"san-vicent-del-raspeig"=>"Сан-Висенте-дель-Распеч",
"sagunto"=>"Сагунто",
"paterna"=>"Патерна",
"orihuela"=>"Ориуэла",
"gandia"=>"Гандия",
"elda"=>"Эльда",
"elche"=>"Эльче",
"castelló-de-la-plana"=>"Кастельон-де-ла-Плана",
"benidorm"=>"Бенидорм",
"alicante"=>"Аликанте",
"alcoy"=>"Алькой",
"groa-de-murviedro"=>"Гроа-де-Мурвиедре",
 ], 
 '3114710' => [
 "oviedo"=>"Овьедо",
"gijón"=>"Хихон",
"avilés"=>"Авилес",
 ], 
 '3115609' => [
 "pamplona"=>"Памплона",
 ], 
 '3117732' => [
 "villaverde"=>"Вильяверде",
"vicálvaro"=>"Викальваро",
"valdemoro"=>"Вальдеморо",
"rivas-vaciamadrid"=>"Ривас-Васиамадрид",
"torrejón-de-ardoz"=>"Торрехон-де-Ардос",
"tetuán-de-las-victorias"=>"Тэтуан-де-лас-викториас",
"san-sebastián-de-los-reyes"=>"Сан-Себастьян-де-лос-Рейес",
"puente-de-vallecas"=>"Пуэнте-де-Вальекас",
"pozuelo-de-alarcón"=>"Посуэло-де-Аларкон",
"parla"=>"Парла",
"móstoles"=>"Мостолес",
"moratalaz"=>"Мораталаз",
"majadahonda"=>"Махадаонда",
"madrid"=>"Мадрид",
"leganés"=>"Леганес",
"las-rozas-de-madrid"=>"Лас-Росас-де-Мадрид",
"hortaleza"=>"Орталеза",
"getafe"=>"Хетафе",
"fuenlabrada"=>"Фуэнлабрада",
"coslada"=>"Кослада",
"collado-villalba"=>"Кольядо-Вильяльба",
"ciudad-lineal"=>"Сьюдад-Лайнер",
"chamartín"=>"Чамартин",
"arganda"=>"Арганда",
"aranjuez"=>"Аранхуэс",
"alcorcón"=>"Алькоркон",
"alcobendas"=>"Алькобендас",
"alcalá-de-henares"=>"Алькала-де-Энарес",
"moncloa-aravaca"=>"Монклоа-Аравака",
"arganzuela"=>"Аргансуэла",
"san-blas"=>"Сан-Блас",
"latina"=>"Латина",
"usera"=>"Юсера",
"salamanca"=>"Саламанка",
"chamberí"=>"Чембери",
"carabanchel"=>"Карабанчель",
"city-center"=>"Сити Центр",
"retiro"=>"Ретиро",
"fuencarral-el-pardo"=>"Фуэнкорал-Эль-Пардо",
"villa-de-vallecas"=>"Вилья-де-Вальекас",
 ], 
 '3336897' => [
 "logroño"=>"Логроньо",
 ], 
 '3336898' => [
 "torrelavega"=>"Торрелавега",
"santander"=>"Сантандер",
 ], 
 '3336899' => [
 "zaragoza"=>"Сарагоса",
"huesca"=>"Уэска",
"delicias"=>"Дэлициас",
 ], 
 '3336900' => [
 "zamora"=>"Замора",
"valladolid"=>"Вальядолид",
"segovia"=>"Сеговия",
"salamanca"=>"Salamanca",
"ponferrada"=>"Понферрада",
"palencia"=>"Паленсия",
"león"=>"Леон",
"burgos"=>"Бургос",
"ávila"=>"Авила",
 ], 
 '3336901' => [
 "vilanova-i-la-geltrú"=>"Вильянуэва и Ла Гелтру",
"viladecans"=>"Виладеканс",
"terrassa"=>"Тарраса",
"tarragona"=>"Таррагона",
"cerdanyola-del-vallès"=>"Серданьола-дель-Вальес",
"santa-coloma-de-gramenet"=>"Санта-Колома-де-Граменет",
"sant-cugat-del-vallès"=>"Сан-Кугат-дель-Вальес",
"sant-boi-de-llobregat"=>"Сан-Бой-де-Льобрегат",
"sant-andreu-de-palomar"=>"Сан-Андреу-де-Паломар",
"sabadell"=>"Сабадель",
"rubí"=>"Руби",
"reus"=>"Реус",
"mollet-del-vallès"=>"Мольет-дель-Вальес",
"mataró"=>"Матаро",
"manresa"=>"Манреса",
"lleida"=>"Льейда",
"lhospitalet-de-llobregat"=>"Оспиталет-де-Льобрегат",
"granollers"=>"Гранольерс",
"gràcia"=>"Грасиа",
"girona"=>"Жирона",
"el-prat-de-llobregat"=>"Эль-Прат-де-Льобрегат",
"cornellà-de-llobregat"=>"Корнелья-де-Льобрегат",
"castelldefels"=>"Кастельдефельс",
"barcelona"=>"Барселона",
"badalona"=>"Бадалона",
"nou-barris"=>"Ноу-Баррис",
"eixample"=>"Эшампле",
"les-corts"=>"Лес Кортс",
"sarrià-sant-gervasi"=>"Саррия-Сант-Жерваси",
"horta-guinardó"=>"Орта-Гинардо",
"sants-montjuïc"=>"Сантс-Монтжуик",
"sant-martí"=>"Сан-Марти",
"ciutat-vella"=>"Ciutat Vella",
 ], 
 '3336902' => [
 "vigo"=>"Виго",
"santiago-de-compostela"=>"Сантьяго-де-Компостела",
"pontevedra"=>"Понтеведра",
"ourense"=>"Оренсе",
"lugo"=>"Луго",
"a-coruña"=>"Ла-Корунья",
"ferrol"=>"Ферроль",
 ], 
 '3336903' => [
 "barakaldo"=>"Баракальдо",
"irun"=>"Ирун",
"getxo"=>"Гечо",
"bilbao"=>"Бильбао",
"algorta"=>"Альгорта",
"santutxu"=>"Сантуксу",
"donostia--san-sebastián"=>"Сан-Себастьян",
"gasteiz--vitoria"=>"Витория-Гастейс",
 ], 
 '6362988' => [
 "melilla"=>"Мелилья",
 ], 
];