<?php 

  return [
  '2985244' => [
 "toulon"=>"Тулон",
"nice"=>"Ницца",
"marseille"=>"Марсель",
"la-seyne-sur-mer"=>"Ла-Сен-сюр-Мер",
"hyères"=>"Йер",
"fréjus"=>"Фрежюс",
"cannes"=>"Канны",
"avignon"=>"Авиньон",
"arles"=>"Арль",
"antibes"=>"Антиб",
"aix-en-provence"=>"Экс-ан-Прованс",
"marseille-08"=>"Марсель 08",
"marseille-10"=>"Марсель 10",
"marseille-09"=>"Марсель 09",
"marseille-11"=>"Марсель 11",
"marseille-12"=>"Марсель 12",
"marseille-13"=>"Марсель 13",
"marseille-14"=>"Марсель 14",
"marseille-15"=>"Марсель 15",
 ], 
 '2988289' => [
 "saint-nazaire"=>"Сен-Назер",
"nantes"=>"Нант",
"le-mans"=>"Ле-Ман",
"laval"=>"Лаваль",
"la-roche-sur-yon"=>"Ла-Рош-сюр-Йон",
"cholet"=>"Шоле",
"angers"=>"Анже",
 ], 
 '3012874' => [
 "vitry-sur-seine"=>"Витри-сюр-Сен",
"versailles"=>"Версаль",
"sartrouville"=>"Сартрувиль",
"sarcelles"=>"Сарсель",
"saint-maur-des-fossés"=>"Сен-Мор-де-Фоссе",
"saint-denis"=>"Сен-Дени",
"rueil-malmaison"=>"Рюэй-Мальмезон",
"paris"=>"Париж",
"pantin"=>"Пантен",
"noisy-le-grand"=>"Нуази-ле-Гран",
"neuilly-sur-seine"=>"Нёйи-сюр-Сен",
"nanterre"=>"Нантер",
"montreuil"=>"Монтрёй",
"meaux"=>"Мо",
"maisons-alfort"=>"Мезон-Альфор",
"levallois-perret"=>"Леваллуа-Перре",
"ivry-sur-seine"=>"Иври-сюр-Сен",
"issy-les-moulineaux"=>"Исси-Ле-Мулино",
"fontenay-sous-bois"=>"Фонтене-су-Буа",
"évry"=>"Эври",
"drancy"=>"Дранси",
"créteil"=>"Кретей",
"courbevoie"=>"Курбевуа",
"colombes"=>"Коломб",
"clichy"=>"Клиши",
"clamart"=>"Кламар",
"champigny-sur-marne"=>"Шампиньи-Сюр-Марн",
"cergy"=>"Сержи",
"boulogne-billancourt"=>"Булонь-Бийанкур",
"aulnay-sous-bois"=>"Оне-су-Буа",
"aubervilliers"=>"Обервилье",
"asnières-sur-seine"=>"Аньер-сюр-Сен",
"argenteuil"=>"Аржантёй",
"antony"=>"Антони",
"saint-quentin-en-yvelines"=>"Сен-Кантен-ан-Ивелин",
"cergy-pontoise"=>"Сержи-Понтуаз",
 ], 
 '3023519' => [
 "ajaccio"=>"Аяччо",
 ], 
 '3027939' => [
 "tours"=>"Тур",
"orléans"=>"Орлеан",
"châteauroux"=>"Шатору",
"bourges"=>"Бурж",
"blois"=>"Блуа",
 ], 
 '3030293' => [
 "vannes"=>"Ванн",
"saint-malo"=>"Сен-Мало",
"saint-brieuc"=>"Сен-Бриё",
"rennes"=>"Ренн",
"quimper"=>"Кемпер",
"lorient"=>"Лорьян",
"brest"=>"Брест",
 ], 
 '11071619' => [
 "dijon"=>"Дижон",
"besançon"=>"Безансон",
"belfort"=>"Бельфор",
 ], 
 '11071620' => [
 "poitiers"=>"Пуатье",
"pessac"=>"Пессак",
"pau"=>"По",
"niort"=>"Ньор",
"mérignac"=>"Мериньяк",
"limoges"=>"Лимож",
"la-rochelle"=>"Ля-Рошель",
"brive-la-gaillarde"=>"Брив-ла-Гайард",
"bordeaux"=>"Бордо",
 ], 
 '11071621' => [
 "rouen"=>"Руан",
"le-havre"=>"Гавр",
"évreux"=>"Эврё",
"caen"=>"Кан",
 ], 
 '11071622' => [
 "troyes"=>"Труа",
"strasbourg"=>"Страсбург",
"reims"=>"Реймс",
"nancy"=>"Нанси",
"mulhouse"=>"Мюлуз",
"metz"=>"Мец",
"colmar"=>"Кольмар",
"charleville-mézières"=>"Шарлевиль-Мезьер",
"châlons-en-champagne"=>"Шалон-ан-Шампань",
 ], 
 '11071623' => [
 "toulouse"=>"Тулуза",
"tarbes"=>"Тарб",
"perpignan"=>"Перпиньян",
"nîmes"=>"Ним",
"narbonne"=>"Нарбонн",
"montpellier"=>"Монпелье",
"montauban"=>"Монтобан",
"béziers"=>"Безье",
"albi"=>"Альби",
 ], 
 '11071624' => [
 "tourcoing"=>"Туркуэн",
"saint-quentin"=>"Сен-Кантен",
"roubaix"=>"Рубе",
"lille"=>"Лилль",
"dunkerque"=>"Дюнкерк",
"calais"=>"Кале",
"beauvais"=>"Бове",
"amiens"=>"Амьен",
"villeneuve-dascq"=>"Вильнёв-д\\\'Аск",
 ], 
 '11071625' => [
 "villeurbanne"=>"Вийёрбан",
"vénissieux"=>"Венисьё",
"valence"=>"Валанс",
"saint-étienne"=>"Сент-Этьен",
"lyon"=>"Лион",
"grenoble"=>"Гренобль",
"clermont-ferrand"=>"Клермон-Ферран",
"chambéry"=>"Шамбери",
 ], 
];