<?php 

  return [
  '2523119' => [
 "vittoria"=>"Виттория",
"trapani"=>"Трапани",
"siracusa"=>"Сиракузы",
"ragusa"=>"Рагуза",
"palermo"=>"Палермо",
"messina"=>"Мессина",
"marsala"=>"Марсала",
"gela"=>"Джела",
"catania"=>"Катания",
"caltanissetta"=>"Кальтаниссетта",
"bagheria"=>"Багерия",
 ], 
 '2523228' => [
 "quartu-santelena"=>"Куарту-Сант-Элена",
"cagliari"=>"Кальяри",
"sassari"=>"Сассари",
 ], 
 '2525468' => [
 "reggio-calabria"=>"Реджо-Калабрия",
"nicastro-sambiase"=>"Никастро-Самбиаз",
"cosenza"=>"Козенца",
"catanzaro"=>"Катанзаро",
"lamezia-terme"=>"Ламеция-Терме",
 ], 
 '3164604' => [
 "vicenza"=>"Виченца",
"verona"=>"Верона",
"venice"=>"Венеция",
"treviso"=>"Тревизо",
"padova"=>"Падуя",
"mestre"=>"Местре",
 ], 
 '3165048' => [
 "terni"=>"Терни",
"perugia"=>"Перуджа",
 ], 
 '3165244' => [
 "trento"=>"Тренто",
"bolzano"=>"Больцано",
 ], 
 '3165361' => [
 "prato"=>"Прато",
"pistoia"=>"Пистоя",
"pisa"=>"Пиза",
"massa"=>"Масса",
"lucca"=>"Лукка",
"livorno"=>"Ливорно",
"grosseto"=>"Гроссето",
"florence"=>"Флоренция",
"carrara"=>"Каррара",
"arezzo"=>"Ареццо",
 ], 
 '3169778' => [
 "trani"=>"Трани",
"taranto"=>"Таранто",
"san-severo"=>"Сан-Северо",
"molfetta"=>"Мольфетта",
"manfredonia"=>"Манфредония",
"lecce"=>"Лечче",
"foggia"=>"Фоджа",
"cerignola"=>"Чериньола",
"brindisi"=>"Бриндизи",
"bitonto"=>"Битонто",
"bisceglie"=>"Бишелье",
"barletta"=>"Барлетта",
"bari"=>"Бари",
"andria"=>"Андрия",
"altamura"=>"Альтамура",
 ], 
 '3170831' => [
 "turin"=>"Турин",
"novara"=>"Новара",
"asti"=>"Асти",
"alessandria"=>"Алессандрия",
 ], 
 '3174004' => [
 "pesaro"=>"Пезаро",
"ancona"=>"Анкона",
 ], 
 '3174618' => [
 "vigevano"=>"Виджевано",
"varese"=>"Варесе",
"sesto-san-giovanni"=>"Сесто-Сан-Джованни",
"pavia"=>"Павия",
"monza"=>"Монца",
"milano"=>"Милан",
"legnano"=>"Леньяно",
"gallarate"=>"Галларате",
"cremona"=>"Кремона",
"como"=>"Комо",
"cinisello-balsamo"=>"Чинизелло-Бальсамо",
"busto-arsizio"=>"Бусто-Арсицио",
"brescia"=>"Брешиа",
"bergamo"=>"Бергамо",
 ], 
 '3174725' => [
 "savona"=>"Савона",
"la-spezia"=>"Специя",
"genoa"=>"Генуя",
 ], 
 '3174976' => [
 "rome"=>"Рим",
"lido-di-ostia"=>"Лидо-ди-Остия",
"latina"=>"Латина",
"acilia-castel-fusano-ostia-antica"=>"Ацилия-Кастель Фузано-Остия Антика",
"guidonia-montecelio"=>"Гуидония-Монтечельо",
 ], 
 '3176525' => [
 "udine"=>"Удине",
"trieste"=>"Триест",
 ], 
 '3177401' => [
 "rimini"=>"Римини",
"reggio-nellemilia"=>"Реджо-нель-Эмилия",
"ravenna"=>"Равенна",
"piacenza"=>"Пьяченца",
"parma"=>"Парма",
"modena"=>"Модена",
"imola"=>"Имола",
"forlì"=>"Форли",
"ferrara"=>"Феррара",
"cesena"=>"Чезена",
"carpi-centro"=>"Карпи",
"bologna"=>"Болонья",
 ], 
 '3181042' => [
 "torre-del-greco"=>"Торре-дель-Греко",
"salerno"=>"Салерно",
"portici"=>"Портичи",
"napoli"=>"Неаполь",
"giugliano-in-campania"=>"Джульяно-ин-Кампанья",
"ercolano"=>"Эрколано",
"castellammare-di-stabia"=>"Кастелламмаре-ди-Стабия",
"casoria"=>"Казория",
"caserta"=>"Казерта",
"aversa"=>"Аверса",
"afragola"=>"Афрагола",
"acerra"=>"Ачерра",
 ], 
 '3182306' => [
 "potenza"=>"Потенца",
"matera"=>"Матера",
 ], 
 '3183560' => [
 "pescara"=>"Пескара",
 ], 
];