<?php 

  return [
  '2743698' => [
 "zoetermeer"=>"Зутермер",
"vlaardingen"=>"Влардинген",
"spijkenisse"=>"Спейкениссе",
"the-hague"=>"Гаага",
"schiedam"=>"Схидам",
"rotterdam"=>"Роттердам",
"leiden"=>"Лейден",
"gouda"=>"Гауда",
"dordrecht"=>"Дордрехт",
"delft"=>"Делфт",
"delfshaven"=>"Дельфсхавен",
"capelle-aan-den-ijssel"=>"Капелле ан ден Эйссел",
"alphen-aan-den-rijn"=>"Алфен-ан-де-Рейн",
 ], 
 '2745909' => [
 "zeist"=>"Зейст",
"veenendaal"=>"Венендал",
"utrecht"=>"Утрехт",
"nieuwegein"=>"Ньивегейн",
"amersfoort"=>"Амерсфорт",
 ], 
 '2748838' => [
 "zwolle"=>"Зволле",
"hengelo"=>"Хенгело",
"hardenberg"=>"Харденберг",
"enschede"=>"Энсхеде",
"deventer"=>"Девентер",
"almelo"=>"Алмело",
 ], 
 '2749879' => [
 "zaanstad"=>"Занстад",
"zaandam"=>"Зандам",
"velsen-zuid"=>"Велсен-Зёйд",
"purmerend"=>"Пюрмеренд",
"hoorn"=>"Хорн",
"hoofddorp"=>"Хофддорп",
"hilversum"=>"Хилверсюм",
"haarlem"=>"Харлем",
"den-helder"=>"Ден-Хелдер",
"amsterdam"=>"Амстердам",
"amstelveen"=>"Амстелвен",
"alkmaar"=>"Алкмар",
"amsterdam-zuidoost"=>"Амстердам-Зюйдост",
 ], 
 '2749990' => [
 "tilburg"=>"Тилбург",
"s-hertogenbosch"=>"Хертогенбос",
"roosendaal"=>"Розендал",
"oss"=>"Осс",
"oosterhout"=>"Остерхаут",
"helmond"=>"Хелмонд",
"eindhoven"=>"Эйндховен",
"breda"=>"Бреда",
"bergen-op-zoom"=>"Берген-оп-Зом",
 ], 
 '2751596' => [
 "venlo"=>"Венло",
"maastricht"=>"Маастрихт",
"heerlen"=>"Херлен",
"born"=>"Борн",
 ], 
 '2755249' => [
 "groningen"=>"Гронинген",
 ], 
 '2755634' => [
 "nijmegen"=>"Неймеген",
"ede"=>"Эде",
"arnhem"=>"Арнем",
"apeldoorn"=>"Апелдорн",
 ], 
 '2755812' => [
 "leeuwarden"=>"Леуварден",
 ], 
 '2756631' => [
 "emmen"=>"Эммен",
"assen"=>"Ассен",
 ], 
 '3319179' => [
 "lelystad"=>"Лелистад",
"almere-stad"=>"Алмере-Стад",
 ], 
];