<?php

  return [
      "focșani" => "Фокшани",
      "râmnicu_vâlcea" => "Рымнику-Вылча",
      "vaslui" => "Васлуй",
      "tulcea" => "Тулча",
      "timişoara" => "Тимишоара",
      "suceava" => "Сучава",
      "sibiu" => "Сибиу",
      "satu_mare" => "Сату Маре",
      "zalău" => "Залэу",
      "ploieşti" => "Плоешти",
      "slatina" => "Слатина",
      "roman" => "Роман",
      "târgu-mureş" => "Тыргу-Муреш",
      "drobeta-turnu_severin" => "Дробета-Турну-Северин",
      "baia_mare" => "Бая-Маре",
      "iaşi" => "Яссы",
      "slobozia" => "Слобозия",
      "hunedoara" => "Хунедоара",
      "târgu_jiu" => "Тыргу-Жиу",
      "giurgiu" => "Джурджу",
      "galaţi" => "Галац",
      "craiova" => "Крайова",
      "târgovişte" => "Тырговиште",
      "sfântu-gheorghe" => "Сфынту-Георге",
      "constanţa" => "Констанца",
      "turda" => "Турда",
      "reşiţa" => "Ресита",
      "buzău" => "Бузэу",
      "bucharest" => "Бухарест",
      "braşov" => "Брашов",
      "brăila" => "Брэила",
      "botoşani" => "Ботошани",
      "bistrita" => "Бистрица",
      "oradea" => "Орадя",
      "bacău" => "Бакэу",
      "piteşti" => "Питешти",
      "arad" => "Арад",
      "alba_iulia" => "Алба-Юлия",
];
