<?php

  return [
      "zhytomyr"=>"Житомир",
      "zaporizhzhya"=>"Запорожье",
      "uzhhorod"=>"Ужгород",
      "novovolyns’k"=>"Нововолынск",
      "vinnytsya"=>"Винница",
      "ternopil’"=>"Тэрнополь",
      "sumy"=>"Сумы",
      "sevastopol"=>"Севастополь",
      "rivne"=>"Ровно",
      "poltava"=>"Полтава",
      "odessa"=>"Одесса",
      "pervomays’k"=>"Первомайск",
      "stryi"=>"Стрый",
      "syevyerodonets’k"=>"Северодонецк",
      "fastiv"=>"Фастов",
      "kyiv"=>"Киев",
      "yevpatoriya"=>"Евпатория",
      "oleksandriya"=>"Александрия",
      "khmel’nyts’kyy"=>"Хмельницкий",
      "nova_kakhovka"=>"Новая Каховка",
      "lozova"=>"Лозовая",
      "kolomyya"=>"Коломыя",
      "druzhkivka"=>"Дружковка",
      "zhovti_vody"=>"Желтые Воды",
      "chernivtsi"=>"Черновцы",
      "pryluky"=>"Прилуки",
      "uman’"=>"Умань",
];
