<?php 

  return [
 'razgrad'=>'Разград',
 'montana'=>'Монтана',
 'vratsa'=>'Враца',
 'varna'=>'Варна',
 'dobrich'=>'Добрич',
 'sofia-province'=>'Софійська область',
 'ruse'=>'Русі',
 'plovdiv'=>'Пловдив',
 'pleven'=>'Плевен',
 'pernik'=>'Пірник',
 'pazardzhik'=>'Пазарджик',
 'lovech'=>'Ловеч',
 'sofia'=>'Софія',
 'burgas'=>'Бургас',
 'blagoevgrad'=>'Благоевград',
 'gabrovo'=>'Габрово',
 'kardzhali'=>'Киржалі',
 'kyustendil'=>'Кюстенділ',
 'shumen'=>'Шумен',
 'silistra'=>'Силистра',
 'sliven'=>'Слівен',
 'smolyan'=>'Смолян',
 'stara-zagora'=>'Стара Загора',
 'targovishte'=>'Тарговіште',
 'veliko-tarnovo'=>'Велико Тирнове',
 'vidin'=>'Відін',
 'yambol'=>'Ямбол',
 ];