<?php 

  return [
 'zurich'=>'Цюріх',
 'vaud'=>'Во',
 'valais'=>'Вале',
 'uri'=>'Урі',
 'ticino'=>'Тичино',
 'thurgau'=>'Тургау',
 'solothurn'=>'Золотурн',
 'schwyz'=>'Швіц',
 'schaffhausen'=>'Шаффхаузен',
 'saint-gallen'=>'Санкт Галлен',
 'obwalden'=>'Обвальден',
 'nidwalden'=>'Нідвальден',
 'neuchâtel'=>'Невшатель',
 'lucerne'=>'Люцерна',
 'jura'=>'Юра',
 'grisons'=>'Гризони',
 'glarus'=>'Гларус',
 'geneva'=>'Женева',
 'fribourg'=>'Фрібург',
 'bern'=>'Берн',
 'basel-city'=>'Базель Сіті',
 'basel-landschaft'=>'Базель Ланд',
 'appenzell-ausserrhoden'=>'Аппенцелль Ауссерроден',
 'appenzell-innerrhoden'=>'Аппенцелль Іннерроден',
 'aargau'=>'Ааргау',
 'zug'=>'Цуг',
 ];