<?php 

  return [
 'pays-de-la-loire'=>'Плати Луари',
 'corsica'=>'Корсика',
 'brittany'=>'Бретань',
 'burgundy'=>'Бургундія',
 'aquitaine'=>'Аквітання',
 'lower-normandy'=>'Нижня Нормандія',
 'alsace'=>'Ельзас',
 'languedoc-roussillon'=>'Лангедок Руссільон',
 'nord-pas-de-calais'=>'Північ Па де Кале',
 'auvergne'=>'Овернь',
 'rhône-alpes'=>'Рона Альпи',
 'poitou-charentes'=>'Пуату Шарант',
 'picardie'=>'Пікардія',
 'midi-pyrénées'=>'Південь Піренеї',
 'lorraine'=>'Лотарингія',
 'limousin'=>'Лімузен',
 'upper-normandy'=>'Верхня Нормандія',
 'franche-comté'=>'Франш Конте',
 'champagne-ardenne'=>'Шампанське Арденни',
 'île-de-france'=>'Іль де Франс',
 'centre'=>'Центр',
 'provence-alpes-côte-dazur'=>'Прованс Альпи Лазурний Берег',
 ];