<?php 

  return [
 'ungheni'=>'Унгень',
 'teleneşti'=>'Теленешти',
 'taraclia'=>'Тараклія',
 'ştefan-vodă'=>'Штефан Водський',
 'strășeni'=>'Страшені',
 'soroca'=>'Сороки',
 'rîşcani'=>'Ришкані',
 'rezina'=>'Гума',
 'orhei'=>'Оргей',
 'ocniţa'=>'Вікниця',
 'anenii-noi'=>'Нові Анени',
 'nisporeni'=>'Нiспорени',
 'leova'=>'Леова',
 'sîngerei'=>'Синжерея',
 'criuleni'=>'Кріулен',
 'laloveni'=>'Яловени',
 'chişinău'=>'Кишинів',
 'căuşeni'=>'Каушани',
 'cantemir'=>'Кантемір',
 'cahul'=>'Кагул',
 'glodeni'=>'Гладені',
 'făleşti'=>'Фелешть',
 'dubăsari'=>'Дубоссари',
 'drochia'=>'Дрокія',
 'donduşeni'=>'Дондюшани',
 'cimişlia'=>'Чимішлія',
 'briceni'=>'Брічені',
 'basarabeasca'=>'Бессарабка',
 'hînceşti'=>'Хинчешти',
 'şoldăneşti'=>'Шолданештський район',
 'stînga-nistrului'=>'Придністровья',
 'găgăuzia'=>'Гагаузія',
 'bender'=>'Бендери',
 'bălţi'=>'Більці',
 'edineţ'=>'Єдинці',
 'floreşti'=>'Флорешти',
 ];