<?php 

  return [
 'rožaje'=>'Рожае',
 'žabljak'=>'Жабляк',
 'ulcinj'=>'Улцінь',
 'tivat'=>'Тіват',
 'podgorica'=>'Підгориця',
 'šavnik'=>'Шавник',
 'plužine'=>'Плужині',
 'pljevlja'=>'Плевля',
 'plav'=>'Плав',
 'nikšić'=>'Нікшич',
 'mojkovac'=>'Мойковаць',
 'kotor'=>'Котор',
 'kolašin'=>'Колашин',
 'berane'=>'Берані',
 'herceg-novi'=>'Герцег Нові',
 'danilovgrad'=>'Даниловград',
 'cetinje'=>'Цітіння',
 'budva'=>'Будва',
 'bijelo-polje'=>'Бієло Поле',
 'bar'=>'Бар',
 'andrijevica'=>'Андрієвиця',
 'gusinje'=>'Гусіні',
 'petnjica'=>'Пьятниця',
 ];