<?php 

  return [
 'vrancea'=>'Вранча',
 'vâlcea'=>'Вилча',
 'vaslui'=>'Васлуй',
 'tulcea'=>'Тулча',
 'timiş'=>'Тіміш',
 'teleorman'=>'Телеорман',
 'suceava'=>'Сучава',
 'sibiu'=>'Сібіу',
 'satu-mare'=>'Сату Маре',
 'sălaj'=>'Селадж',
 'prahova'=>'Прахова',
 'olt'=>'Олт',
 'neamţ'=>'Неамц',
 'mureş'=>'Муреш',
 'mehedinţi'=>'Мехединці',
 'maramureş'=>'Марамуреш',
 'ialomiţa'=>'Яломиця',
 'hunedoara'=>'Хунедоара',
 'harghita'=>'Харгіта',
 'gorj'=>'Горж',
 'giurgiu'=>'Джурдж',
 'galaţi'=>'Галац',
 'dolj'=>'Долж',
 'dâmboviţa'=>'Димбовиця',
 'covasna'=>'Ковасна',
 'constanța'=>'Констанца',
 'cluj'=>'Клуж',
 'caraş-severin'=>'Караш Северін',
 'călăraşi'=>'Келераші',
 'buzău'=>'Бузеу',
 'braşov'=>'Брашов',
 'brăila'=>'Бреїла',
 'botoşani'=>'Ботошані',
 'bistriţa-năsăud'=>'Бістриця Несеуд',
 'bihor'=>'Біхор',
 'bacău'=>'Бакау',
 'argeş'=>'Аргеш',
 'arad'=>'Арад',
 'alba'=>'Альба',
 'ilfov'=>'Ільфов',
 'bucureşti'=>'Бухарест',
 'iaşi'=>'Яси',
 ];