<?php 

  return [
 "razgrad_reg"=>"Razgrad",
"montana_reg"=>"Montana",
"vratsa_reg"=>"Vratsa",
"varna_reg"=>"Varna",
"dobrich_reg"=>"Dobrich",
"sofia_province_reg"=>"Sofia Province",
"ruse_reg"=>"Ruse",
"plovdiv_reg"=>"Plovdiv",
"pleven_reg"=>"Pleven",
"pernik_reg"=>"Pernik",
"pazardzhik_reg"=>"Pazardzhik",
"lovech_reg"=>"Lovech",
"khaskovo_reg"=>"Khaskovo",
"sofia_reg"=>"Sofia",
"burgas_reg"=>"Burgas",
"blagoevgrad_reg"=>"Blagoevgrad",
"gabrovo_reg"=>"Gabrovo",
"kardzhali_reg"=>"Kardzhali",
"kyustendil_reg"=>"Kyustendil",
"shumen_reg"=>"Shumen",
"silistra_reg"=>"Silistra",
"sliven_reg"=>"Sliven",
"smolyan_reg"=>"Smolyan",
"stara_zagora_reg"=>"Stara Zagora",
"targovishte_reg"=>"Targovishte",
"veliko_tarnovo_reg"=>"Veliko Tarnovo",
"vidin_reg"=>"Vidin",
"yambol_reg"=>"Yambol",
];