<?php 

  return [
 "razgrad"=>"Razgrad",
"montana"=>"Montana",
"vratsa"=>"Vratsa",
"varna"=>"Varna",
"dobrich"=>"Dobrich",
"sofia_province"=>"Sofia Province",
"ruse"=>"Ruse",
"plovdiv"=>"Plovdiv",
"pleven"=>"Pleven",
"pernik"=>"Pernik",
"pazardzhik"=>"Pazardzhik",
"lovech"=>"Lovech",
"khaskovo"=>"Khaskovo",
"sofia"=>"Sofia",
"burgas"=>"Burgas",
"blagoevgrad"=>"Blagoevgrad",
"gabrovo"=>"Gabrovo",
"kardzhali"=>"Kardzhali",
"kyustendil"=>"Kyustendil",
"shumen"=>"Shumen",
"silistra"=>"Silistra",
"sliven"=>"Sliven",
"smolyan"=>"Smolyan",
"stara_zagora"=>"Stara Zagora",
"targovishte"=>"Targovishte",
"veliko_tarnovo"=>"Veliko Tarnovo",
"vidin"=>"Vidin",
"yambol"=>"Yambol",
];