<?php 

  return [
 "zurich"=>"Zurich",
"zug"=>"Zug",
"vaud"=>"Vaud",
"valais"=>"Valais",
"uri"=>"Uri",
"ticino"=>"Ticino",
"thurgau"=>"Thurgau",
"solothurn"=>"Solothurn",
"schwyz"=>"Schwyz",
"schaffhausen"=>"Schaffhausen",
"saint_gallen"=>"Saint Gallen",
"obwalden"=>"Obwalden",
"nidwalden"=>"Nidwalden",
"neuchâtel"=>"Neuchâtel",
"lucerne"=>"Lucerne",
"jura"=>"Jura",
"grisons"=>"Grisons",
"glarus"=>"Glarus",
"geneva"=>"Geneva",
"fribourg"=>"Fribourg",
"bern"=>"Bern",
"basel_city"=>"Basel City",
"basel-landschaft"=>"Basel-Landschaft",
"appenzell_ausserrhoden"=>"Appenzell Ausserrhoden",
"appenzell_innerrhoden"=>"Appenzell Innerrhoden",
"aargau"=>"Aargau",
];