<?php 

  return [
 "provence-alpes-côte-dazur"=>"Provence-Alpes-Côte d\'Azur",
"pays-de-la-loire"=>"Pays de la Loire",
"île-de-france"=>"Île-de-France",
"corsica"=>"Corsica",
"centre"=>"Centre",
"brittany"=>"Brittany",
"burgundy"=>"Burgundy",
"aquitaine"=>"Aquitaine",
"lower-normandy"=>"Lower Normandy",
"alsace"=>"Alsace",
"languedoc-roussillon"=>"Languedoc-Roussillon",
"nord-pas-de-calais"=>"Nord-Pas-de-Calais",
"auvergne"=>"Auvergne",
"rhône-alpes"=>"Rhône-Alpes",
"poitou-charentes"=>"Poitou-Charentes",
"picardie"=>"Picardie",
"midi-pyrénées"=>"Midi-Pyrénées",
"lorraine"=>"Lorraine",
"limousin"=>"Limousin",
"upper-normandy"=>"Upper Normandy",
"franche-comté"=>"Franche-Comté",
"champagne-ardenne"=>"Champagne-Ardenne",
];