<?php 

  return [
 "bjelovarsko-bilogorska"=>"Bjelovarsko-Bilogorska",
"brodsko-posavska"=>"Brodsko-Posavska",
"dubrovačko-neretvanska"=>"Dubrovačko-Neretvanska",
"istarska"=>"Istarska",
"karlovačka"=>"Karlovačka",
"koprivničko-križevačka"=>"Koprivničko-Križevačka",
"krapinsko-zagorska"=>"Krapinsko-Zagorska",
"ličko-senjska"=>"Ličko-Senjska",
"međimurska"=>"Međimurska",
"osječko-baranjska"=>"Osječko-Baranjska",
"požeško-slavonska"=>"Požeško-Slavonska",
"primorsko-goranska"=>"Primorsko-Goranska",
"šibensko-kninska"=>"Šibensko-Kninska",
"sisačko-moslavačka"=>"Sisačko-Moslavačka",
"splitsko-dalmatinska"=>"Splitsko-Dalmatinska",
"varaždinska"=>"Varaždinska",
"vukovarsko-srijemska"=>"Vukovarsko-Srijemska",
"zadarska"=>"Zadarska",
"zagrebačka"=>"Zagrebačka",
"grad-zagreb"=>"Grad Zagreb",
"virovitičko-podravska"=>"Virovitičko-Podravska",
];