<?php 

  return [
 "edineţ_reg"=>"Edineţ",
"ungheni_reg"=>"Ungheni",
"teleneşti_reg"=>"Teleneşti",
"taraclia_reg"=>"Taraclia",
"ştefan-vodă_reg"=>"Ştefan-Vodă",
"strășeni_reg"=>"Strășeni",
"soroca_reg"=>"Soroca",
"rîşcani_reg"=>"Rîşcani",
"rezina_reg"=>"Rezina",
"orhei_reg"=>"Orhei",
"ocniţa_reg"=>"Ocniţa",
"anenii_noi_reg"=>"Anenii Noi",
"nisporeni_reg"=>"Nisporeni",
"leova_reg"=>"Leova",
"sîngerei_reg"=>"Sîngerei",
"criuleni_reg"=>"Criuleni",
"laloveni_reg"=>"Laloveni",
"chişinău_reg"=>"Chişinău",
"căuşeni_reg"=>"Căuşeni",
"cantemir_reg"=>"Cantemir",
"călăraşi_reg"=>"Călăraşi",
"cahul_reg"=>"Cahul",
"glodeni_reg"=>"Glodeni",
"floreşti_reg"=>"Floreşti",
"făleşti_reg"=>"Făleşti",
"dubăsari_reg"=>"Dubăsari",
"drochia_reg"=>"Drochia",
"donduşeni_reg"=>"Donduşeni",
"cimişlia_reg"=>"Cimişlia",
"briceni_reg"=>"Briceni",
"basarabeasca_reg"=>"Basarabeasca",
"hînceşti_reg"=>"Hînceşti",
"şoldăneşti_reg"=>"Şoldăneşti",
"stînga_nistrului_reg"=>"Stînga Nistrului",
"găgăuzia_reg"=>"Găgăuzia",
"bender_reg"=>"Bender",
"bălţi_reg"=>"Bălţi",
];