<?php 

  return [
 "edineţ"=>"Edineţ",
"ungheni"=>"Ungheni",
"teleneşti"=>"Teleneşti",
"taraclia"=>"Taraclia",
"ştefan-vodă"=>"Ştefan-Vodă",
"strășeni"=>"Strășeni",
"soroca"=>"Soroca",
"rîşcani"=>"Rîşcani",
"rezina"=>"Rezina",
"orhei"=>"Orhei",
"ocniţa"=>"Ocniţa",
"anenii_noi"=>"Anenii Noi",
"nisporeni"=>"Nisporeni",
"leova"=>"Leova",
"sîngerei"=>"Sîngerei",
"criuleni"=>"Criuleni",
"laloveni"=>"Laloveni",
"chişinău"=>"Chişinău",
"căuşeni"=>"Căuşeni",
"cantemir"=>"Cantemir",
"călăraşi"=>"Călăraşi",
"cahul"=>"Cahul",
"glodeni"=>"Glodeni",
"floreşti"=>"Floreşti",
"făleşti"=>"Făleşti",
"dubăsari"=>"Dubăsari",
"drochia"=>"Drochia",
"donduşeni"=>"Donduşeni",
"cimişlia"=>"Cimişlia",
"briceni"=>"Briceni",
"basarabeasca"=>"Basarabeasca",
"hînceşti"=>"Hînceşti",
"şoldăneşti"=>"Şoldăneşti",
"stînga_nistrului"=>"Stînga Nistrului",
"găgăuzia"=>"Găgăuzia",
"bender"=>"Bender",
"bălţi"=>"Bălţi",
];