<?php 

  return [
 "rožaje"=>"Rožaje",
"žabljak"=>"Žabljak",
"ulcinj"=>"Ulcinj",
"tivat"=>"Tivat",
"podgorica"=>"Podgorica",
"šavnik"=>"Šavnik",
"plužine"=>"Plužine",
"pljevlja"=>"Pljevlja",
"plav"=>"Plav",
"nikšić"=>"Nikšić",
"mojkovac"=>"Mojkovac",
"kotor"=>"Kotor",
"kolašin"=>"Kolašin",
"berane"=>"Berane",
"herceg_novi"=>"Herceg Novi",
"danilovgrad"=>"Danilovgrad",
"cetinje"=>"Cetinje",
"budva"=>"Budva",
"bijelo_polje"=>"Bijelo Polje",
"bar"=>"Bar",
"andrijevica"=>"Andrijevica",
"gusinje"=>"Gusinje",
"petnjica"=>"Petnjica",
];