<?php 

  return [
 "norrbotten"=>"Norrbotten",
"västmanland"=>"Västmanland",
"västernorrland"=>"Västernorrland",
"västerbotten"=>"Västerbotten",
"värmland"=>"Värmland",
"uppsala"=>"Uppsala",
"stockholm"=>"Stockholm",
"södermanland"=>"Södermanland",
"östergötland"=>"Östergötland",
"örebro"=>"Örebro",
"kronoberg"=>"Kronoberg",
"dalarna"=>"Dalarna",
"kalmar"=>"Kalmar",
"jönköping"=>"Jönköping",
"jämtland"=>"Jämtland",
"halland"=>"Halland",
"gotland"=>"Gotland",
"gävleborg"=>"Gävleborg",
"blekinge"=>"Blekinge",
"skåne"=>"Skåne",
"västra-götaland"=>"Västra Götaland",
];