<?php 

  return [
 "zhytomyr"=>"Zhytomyr",
"zaporizhia"=>"Zaporizhia",
"zakarpattia"=>"Zakarpattia",
"volyn"=>"Volyn",
"vinnyts'ka"=>"Vinnyts'ka",
"ternopil"=>"Ternopil",
"sumy"=>"Sumy",
"misto_sevastopol’"=>"Misto Sevastopol’",
"rivne"=>"Rivne",
"poltava"=>"Poltava",
"odessa"=>"Odessa",
"mykolaiv"=>"Mykolaiv",
"lviv"=>"Lviv",
"luhansk"=>"Luhansk",
"kyiv"=>"Kyiv",
"kyiv_city"=>"Kyiv City",
"crimea"=>"Crimea",
"kirovohrad"=>"Kirovohrad",
"khmelnytskyi"=>"Khmelnytskyi",
"kherson"=>"Kherson",
"kharkiv"=>"Kharkiv",
"ivano-frankivsk"=>"Ivano-Frankivsk",
"donetsk"=>"Donetsk",
"dnipropetrovsk"=>"Dnipropetrovsk",
"chernivtsi"=>"Chernivtsi",
"chernihiv"=>"Chernihiv",
"cherkasy"=>"Cherkasy",
];