<?php 

  return [
 "zhytomyr_reg"=>"Zhytomyr",
"zaporizhia_reg"=>"Zaporizhia",
"zakarpattia_reg"=>"Zakarpattia",
"volyn_reg"=>"Volyn",
"vinnyts'ka_reg"=>"Vinnyts'ka",
"ternopil_reg"=>"Ternopil",
"sumy_reg"=>"Sumy",
"misto_sevastopol’_reg"=>"Misto Sevastopol’",
"rivne_reg"=>"Rivne",
"poltava_reg"=>"Poltava",
"odessa_reg"=>"Odessa",
"mykolaiv_reg"=>"Mykolaiv",
"lviv_reg"=>"Lviv",
"luhansk_reg"=>"Luhansk",
"kyiv_reg"=>"Kyiv",
"kyiv_city_reg"=>"Kyiv City",
"crimea_reg"=>"Crimea",
"kirovohrad_reg"=>"Kirovohrad",
"khmelnytskyi_reg"=>"Khmelnytskyi",
"kherson_reg"=>"Kherson",
"kharkiv_reg"=>"Kharkiv",
"ivano-frankivsk_reg"=>"Ivano-Frankivsk",
"donetsk_reg"=>"Donetsk",
"dnipropetrovsk_reg"=>"Dnipropetrovsk",
"chernivtsi_reg"=>"Chernivtsi",
"chernihiv_reg"=>"Chernihiv",
"cherkasy_reg"=>"Cherkasy",
];