<?php 

  return [
 "zurich_reg"=>"Zurich",
"zug_reg"=>"Zug",
"vaud_reg"=>"Vaud",
"valais_reg"=>"Valais",
"uri_reg"=>"Uri",
"ticino_reg"=>"Ticino",
"thurgau_reg"=>"Thurgau",
"solothurn_reg"=>"Solothurn",
"schwyz_reg"=>"Schwyz",
"schaffhausen_reg"=>"Schaffhausen",
"saint_gallen_reg"=>"Saint Gallen",
"obwalden_reg"=>"Obwalden",
"nidwalden_reg"=>"Nidwalden",
"neuchâtel_reg"=>"Neuchâtel",
"lucerne_reg"=>"Lucerne",
"jura_reg"=>"Jura",
"grisons_reg"=>"Grisons",
"glarus_reg"=>"Glarus",
"geneva_reg"=>"Geneva",
"fribourg_reg"=>"Fribourg",
"bern_reg"=>"Bern",
"basel_city_reg"=>"Basel City",
"basel-landschaft_reg"=>"Basel-Landschaft",
"appenzell_ausserrhoden_reg"=>"Appenzell Ausserrhoden",
"appenzell_innerrhoden_reg"=>"Appenzell Innerrhoden",
"aargau_reg"=>"Aargau",
];