<?php 

  return [
 "rožaje_reg"=>"Rožaje",
"žabljak_reg"=>"Žabljak",
"ulcinj_reg"=>"Ulcinj",
"tivat_reg"=>"Tivat",
"podgorica_reg"=>"Podgorica",
"šavnik_reg"=>"Šavnik",
"plužine_reg"=>"Plužine",
"pljevlja_reg"=>"Pljevlja",
"plav_reg"=>"Plav",
"nikšić_reg"=>"Nikšić",
"mojkovac_reg"=>"Mojkovac",
"kotor_reg"=>"Kotor",
"kolašin_reg"=>"Kolašin",
"berane_reg"=>"Berane",
"herceg_novi_reg"=>"Herceg Novi",
"danilovgrad_reg"=>"Danilovgrad",
"cetinje_reg"=>"Cetinje",
"budva_reg"=>"Budva",
"bijelo_polje_reg"=>"Bijelo Polje",
"bar_reg"=>"Bar",
"andrijevica_reg"=>"Andrijevica",
"gusinje_reg"=>"Gusinje",
"petnjica_reg"=>"Petnjica",
];