<?php 

  return [
 "norrbotten_reg"=>"Norrbotten",
"västmanland_reg"=>"Västmanland",
"västernorrland_reg"=>"Västernorrland",
"västerbotten_reg"=>"Västerbotten",
"värmland_reg"=>"Värmland",
"uppsala_reg"=>"Uppsala",
"stockholm_reg"=>"Stockholm",
"södermanland_reg"=>"Södermanland",
"östergötland_reg"=>"Östergötland",
"örebro_reg"=>"Örebro",
"kronoberg_reg"=>"Kronoberg",
"dalarna_reg"=>"Dalarna",
"kalmar_reg"=>"Kalmar",
"jönköping_reg"=>"Jönköping",
"jämtland_reg"=>"Jämtland",
"halland_reg"=>"Halland",
"gotland_reg"=>"Gotland",
"gävleborg_reg"=>"Gävleborg",
"blekinge_reg"=>"Blekinge",
"skåne_reg"=>"Skåne",
"västra_götaland_reg"=>"Västra Götaland",
];