<?php 

  return [
  '5883102' => [
 "calgary"=>"Calgary",
"edmonton"=>"Edmonton",
"fort-mcmurray"=>"Fort McMurray",
"lethbridge"=>"Lethbridge",
"medicine-hat"=>"Medicine Hat",
"red-deer"=>"Red Deer",
"sherwood-park"=>"Sherwood Park",
"st-albert"=>"St. Albert",
 ], 
 '5909050' => [
 "abbotsford"=>"Abbotsford",
"anmore"=>"Anmore",
"burnaby"=>"Burnaby",
"chilliwack"=>"Chilliwack",
"coquitlam"=>"Coquitlam",
"delta"=>"Delta",
"kamloops"=>"Kamloops",
"kelowna"=>"Kelowna",
"langley"=>"Langley",
"maple-ridge"=>"Maple Ridge",
"nanaimo"=>"Nanaimo",
"new-westminster"=>"New Westminster",
"prince-george"=>"Prince George",
"richmond"=>"Richmond",
"surrey"=>"Surrey",
"vancouver"=>"Vancouver",
"victoria"=>"Victoria",
"white-rock"=>"White Rock",
"okanagan"=>"Okanagan",
"ladner"=>"Ladner",
 ], 
 '6065171' => [
 "winnipeg"=>"Winnipeg",
 ], 
 '6087430' => [
 "fredericton"=>"Fredericton",
"moncton"=>"Moncton",
"saint-john"=>"Saint John",
 ], 
 '6091530' => [
 "dartmouth"=>"Dartmouth",
"halifax"=>"Halifax",
"sydney"=>"Sydney",
 ], 
 '6093943' => [
 "ajax"=>"Ajax",
"barrie"=>"Barrie",
"brampton"=>"Brampton",
"brantford"=>"Brantford",
"burlington"=>"Burlington",
"cambridge"=>"Cambridge",
"etobicoke"=>"Etobicoke",
"greater-sudbury"=>"Greater Sudbury",
"guelph"=>"Guelph",
"hamilton"=>"Hamilton",
"kingston"=>"Kingston",
"kitchener"=>"Kitchener",
"london"=>"London",
"markham"=>"Markham",
"milton"=>"Milton",
"mississauga"=>"Mississauga",
"newmarket"=>"Newmarket",
"niagara-falls"=>"Niagara Falls",
"norfolk-county"=>"Norfolk County",
"north-bay"=>"North Bay",
"north-york"=>"North York",
"oakville"=>"Oakville",
"oshawa"=>"Oshawa",
"ottawa"=>"Ottawa",
"peterborough"=>"Peterborough",
"pickering"=>"Pickering",
"richmond-hill"=>"Richmond Hill",
"sarnia"=>"Sarnia",
"sault-ste-marie"=>"Sault Ste. Marie",
"st-catharines"=>"St. Catharines",
"thunder-bay"=>"Thunder Bay",
"toronto"=>"Toronto",
"vaughan"=>"Vaughan",
"waterloo"=>"Waterloo",
"welland"=>"Welland",
"windsor"=>"Windsor",
"scarborough"=>"Scarborough",
"willowdale"=>"Willowdale",
 ], 
 '6115047' => [
 "brossard"=>"Brossard",
"drummondville"=>"Drummondville",
"gatineau"=>"Gatineau",
"granby"=>"Granby",
"laval"=>"Laval",
"longueuil"=>"Longueuil",
"montréal"=>"Montréal",
"repentigny"=>"Repentigny",
"saguenay"=>"Saguenay",
"saint-hyacinthe"=>"Saint-Hyacinthe",
"saint-jean-sur-richelieu"=>"Saint-Jean-sur-Richelieu",
"saint-jérôme"=>"Saint-Jérôme",
"saint-laurent"=>"Saint-Laurent",
"saint-léonard"=>"Saint-Léonard",
"sherbrooke"=>"Sherbrooke",
"terrebonne"=>"Terrebonne",
"trois-rivières"=>"Trois-Rivières",
"québec"=>"Québec",
"lévis"=>"Lévis",
"jonquière"=>"Jonquière",
 ], 
 '6141242' => [
 "regina"=>"Regina",
"saskatoon"=>"Saskatoon",
 ], 
 '6354959' => [
 "st-johns"=>"St. John\'s",
 ], 
];