<?php 

  return [
  '2513413' => [
 "murcia"=>"Murcia",
"molina-de-segura"=>"Molina de Segura",
"lorca"=>"Lorca",
"cartagena"=>"Cartagena",
 ], 
 '2519582' => [
 "ceuta"=>"Ceuta",
 ], 
 '2521383' => [
 "palma"=>"Palma",
"calvià"=>"Calvià",
 ], 
 '2593109' => [
 "vélez-málaga"=>"Vélez-Málaga",
"utrera"=>"Utrera",
"torremolinos"=>"Torremolinos",
"sevilla"=>"Sevilla",
"sanlúcar-de-barrameda"=>"Sanlúcar de Barrameda",
"san-fernando"=>"San Fernando",
"roquetas-de-mar"=>"Roquetas de Mar",
"motril"=>"Motril",
"mijas"=>"Mijas",
"marbella"=>"Marbella",
"málaga"=>"Málaga",
"linares"=>"Linares",
"la-línea-de-la-concepción"=>"La Línea de la Concepción",
"jerez-de-la-frontera"=>"Jerez de la Frontera",
"jaén"=>"Jaén",
"huelva"=>"Huelva",
"granada"=>"Granada",
"fuengirola"=>"Fuengirola",
"estepona"=>"Estepona",
"el-puerto-de-santa-maría"=>"El Puerto de Santa María",
"el-ejido"=>"El Ejido",
"dos-hermanas"=>"Dos Hermanas",
"córdoba"=>"Córdoba",
"chiclana-de-la-frontera"=>"Chiclana de la Frontera",
"campiña"=>"Campiña",
"cadiz"=>"Cadiz",
"benalmádena"=>"Benalmádena",
"almería"=>"Almería",
"algeciras"=>"Algeciras",
"alcalá-de-guadaira"=>"Alcalá de Guadaira",
 ], 
 '2593110' => [
 "telde"=>"Telde",
"santa-lucía"=>"Santa Lucía",
"santa-cruz-de-tenerife"=>"Santa Cruz de Tenerife",
"la-laguna"=>"La Laguna",
"san-bartolomé-de-tirajana"=>"San Bartolomé de Tirajana",
"las-palmas-de-gran-canaria"=>"Las Palmas de Gran Canaria",
"arrecife"=>"Arrecife",
"arona"=>"Arona",
 ], 
 '2593111' => [
 "toledo"=>"Toledo",
"talavera-de-la-reina"=>"Talavera de la Reina",
"puertollano"=>"Puertollano",
"ciudad-real"=>"Ciudad Real",
"albacete"=>"Albacete",
"guadalajara"=>"Guadalajara",
"cuenca"=>"Cuenca",
 ], 
 '2593112' => [
 "mérida"=>"Mérida",
"cáceres"=>"Cáceres",
"badajoz"=>"Badajoz",
 ], 
 '2593113' => [
 "vila-real"=>"Vila-real",
"valencia"=>"Valencia",
"torrevieja"=>"Torrevieja",
"torrent"=>"Torrent",
"san-vicent-del-raspeig"=>"San Vicent del Raspeig",
"sagunto"=>"Sagunto",
"paterna"=>"Paterna",
"orihuela"=>"Orihuela",
"gandia"=>"Gandia",
"elda"=>"Elda",
"elche"=>"Elche",
"castelló-de-la-plana"=>"Castelló de la Plana",
"benidorm"=>"Benidorm",
"alicante"=>"Alicante",
"alcoy"=>"Alcoy",
"groa-de-murviedro"=>"Groa de Murviedro",
 ], 
 '3114710' => [
 "oviedo"=>"Oviedo",
"gijón"=>"Gijón",
"avilés"=>"Avilés",
 ], 
 '3115609' => [
 "pamplona"=>"Pamplona",
 ], 
 '3117732' => [
 "villaverde"=>"Villaverde",
"vicálvaro"=>"Vicálvaro",
"valdemoro"=>"Valdemoro",
"rivas-vaciamadrid"=>"Rivas-Vaciamadrid",
"torrejón-de-ardoz"=>"Torrejón de Ardoz",
"tetuán-de-las-victorias"=>"Tetuán de las Victorias",
"san-sebastián-de-los-reyes"=>"San Sebastián de los Reyes",
"puente-de-vallecas"=>"Puente de Vallecas",
"pozuelo-de-alarcón"=>"Pozuelo de Alarcón",
"parla"=>"Parla",
"móstoles"=>"Móstoles",
"moratalaz"=>"Moratalaz",
"majadahonda"=>"Majadahonda",
"madrid"=>"Madrid",
"leganés"=>"Leganés",
"las-rozas-de-madrid"=>"Las Rozas de Madrid",
"hortaleza"=>"Hortaleza",
"getafe"=>"Getafe",
"fuenlabrada"=>"Fuenlabrada",
"coslada"=>"Coslada",
"collado-villalba"=>"Collado-Villalba",
"ciudad-lineal"=>"Ciudad Lineal",
"chamartín"=>"Chamartín",
"arganda"=>"Arganda",
"aranjuez"=>"Aranjuez",
"alcorcón"=>"Alcorcón",
"alcobendas"=>"Alcobendas",
"alcalá-de-henares"=>"Alcalá de Henares",
"moncloa-aravaca"=>"Moncloa-Aravaca",
"arganzuela"=>"Arganzuela",
"san-blas"=>"San Blas",
"latina"=>"Latina",
"usera"=>"Usera",
"salamanca"=>"Salamanca",
"chamberí"=>"Chamberí",
"carabanchel"=>"Carabanchel",
"city-center"=>"City Center",
"retiro"=>"Retiro",
"fuencarral-el-pardo"=>"Fuencarral-El Pardo",
"villa-de-vallecas"=>"Villa de Vallecas",
 ], 
 '3336897' => [
 "logroño"=>"Logroño",
 ], 
 '3336898' => [
 "torrelavega"=>"Torrelavega",
"santander"=>"Santander",
 ], 
 '3336899' => [
 "zaragoza"=>"Zaragoza",
"huesca"=>"Huesca",
"delicias"=>"Delicias",
 ], 
 '3336900' => [
 "zamora"=>"Zamora",
"valladolid"=>"Valladolid",
"segovia"=>"Segovia",
"salamanca"=>"Salamanca",
"ponferrada"=>"Ponferrada",
"palencia"=>"Palencia",
"león"=>"León",
"burgos"=>"Burgos",
"ávila"=>"Ávila",
 ], 
 '3336901' => [
 "vilanova-i-la-geltrú"=>"Vilanova i la Geltrú",
"viladecans"=>"Viladecans",
"terrassa"=>"Terrassa",
"tarragona"=>"Tarragona",
"cerdanyola-del-vallès"=>"Cerdanyola del Vallès",
"santa-coloma-de-gramenet"=>"Santa Coloma de Gramenet",
"sant-cugat-del-vallès"=>"Sant Cugat del Vallès",
"sant-boi-de-llobregat"=>"Sant Boi de Llobregat",
"sant-andreu-de-palomar"=>"Sant Andreu de Palomar",
"sabadell"=>"Sabadell",
"rubí"=>"Rubí",
"reus"=>"Reus",
"mollet-del-vallès"=>"Mollet del Vallès",
"mataró"=>"Mataró",
"manresa"=>"Manresa",
"lleida"=>"Lleida",
"lhospitalet-de-llobregat"=>"L\'Hospitalet de Llobregat",
"granollers"=>"Granollers",
"gràcia"=>"Gràcia",
"girona"=>"Girona",
"el-prat-de-llobregat"=>"El Prat de Llobregat",
"cornellà-de-llobregat"=>"Cornellà de Llobregat",
"castelldefels"=>"Castelldefels",
"barcelona"=>"Barcelona",
"badalona"=>"Badalona",
"nou-barris"=>"Nou Barris",
"eixample"=>"Eixample",
"les-corts"=>"les Corts",
"sarrià-sant-gervasi"=>"Sarrià-Sant Gervasi",
"horta-guinardó"=>"Horta-Guinardó",
"sants-montjuïc"=>"Sants-Montjuïc",
"sant-martí"=>"Sant Martí",
"ciutat-vella"=>"Ciutat Vella",
 ], 
 '3336902' => [
 "vigo"=>"Vigo",
"santiago-de-compostela"=>"Santiago de Compostela",
"pontevedra"=>"Pontevedra",
"ourense"=>"Ourense",
"lugo"=>"Lugo",
"a-coruña"=>"A Coruña",
"ferrol"=>"Ferrol",
 ], 
 '3336903' => [
 "gasteiz-/-vitoria"=>"Gasteiz / Vitoria",
"barakaldo"=>"Barakaldo",
"donostia-/-san-sebastián"=>"Donostia / San Sebastián",
"irun"=>"Irun",
"getxo"=>"Getxo",
"bilbao"=>"Bilbao",
"algorta"=>"Algorta",
"santutxu"=>"Santutxu",
 ], 
 '6362988' => [
 "melilla"=>"Melilla",
 ], 
];