<?php 

  return [
  '2985244' => [
 "toulon"=>"Toulon",
"nice"=>"Nice",
"marseille"=>"Marseille",
"la-seyne-sur-mer"=>"La Seyne-sur-Mer",
"hyères"=>"Hyères",
"fréjus"=>"Fréjus",
"cannes"=>"Cannes",
"avignon"=>"Avignon",
"arles"=>"Arles",
"antibes"=>"Antibes",
"aix-en-provence"=>"Aix-en-Provence",
"marseille-08"=>"Marseille 08",
"marseille-10"=>"Marseille 10",
"marseille-09"=>"Marseille 09",
"marseille-11"=>"Marseille 11",
"marseille-12"=>"Marseille 12",
"marseille-13"=>"Marseille 13",
"marseille-14"=>"Marseille 14",
"marseille-15"=>"Marseille 15",
 ], 
 '2988289' => [
 "saint-nazaire"=>"Saint-Nazaire",
"nantes"=>"Nantes",
"le-mans"=>"Le Mans",
"laval"=>"Laval",
"la-roche-sur-yon"=>"La Roche-sur-Yon",
"cholet"=>"Cholet",
"angers"=>"Angers",
 ], 
 '3012874' => [
 "vitry-sur-seine"=>"Vitry-sur-Seine",
"versailles"=>"Versailles",
"sartrouville"=>"Sartrouville",
"sarcelles"=>"Sarcelles",
"saint-maur-des-fossés"=>"Saint-Maur-des-Fossés",
"saint-denis"=>"Saint-Denis",
"rueil-malmaison"=>"Rueil-Malmaison",
"paris"=>"Paris",
"pantin"=>"Pantin",
"noisy-le-grand"=>"Noisy-le-Grand",
"neuilly-sur-seine"=>"Neuilly-sur-Seine",
"nanterre"=>"Nanterre",
"montreuil"=>"Montreuil",
"meaux"=>"Meaux",
"maisons-alfort"=>"Maisons-Alfort",
"levallois-perret"=>"Levallois-Perret",
"ivry-sur-seine"=>"Ivry-sur-Seine",
"issy-les-moulineaux"=>"Issy-les-Moulineaux",
"fontenay-sous-bois"=>"Fontenay-sous-Bois",
"évry"=>"Évry",
"drancy"=>"Drancy",
"créteil"=>"Créteil",
"courbevoie"=>"Courbevoie",
"colombes"=>"Colombes",
"clichy"=>"Clichy",
"clamart"=>"Clamart",
"champigny-sur-marne"=>"Champigny-sur-Marne",
"cergy"=>"Cergy",
"boulogne-billancourt"=>"Boulogne-Billancourt",
"aulnay-sous-bois"=>"Aulnay-sous-Bois",
"aubervilliers"=>"Aubervilliers",
"asnières-sur-seine"=>"Asnières-sur-Seine",
"argenteuil"=>"Argenteuil",
"antony"=>"Antony",
"saint-quentin-en-yvelines"=>"Saint-Quentin-en-Yvelines",
"cergy-pontoise"=>"Cergy-Pontoise",
 ], 
 '3023519' => [
 "ajaccio"=>"Ajaccio",
 ], 
 '3027939' => [
 "tours"=>"Tours",
"orléans"=>"Orléans",
"châteauroux"=>"Châteauroux",
"bourges"=>"Bourges",
"blois"=>"Blois",
 ], 
 '3030293' => [
 "vannes"=>"Vannes",
"saint-malo"=>"Saint-Malo",
"saint-brieuc"=>"Saint-Brieuc",
"rennes"=>"Rennes",
"quimper"=>"Quimper",
"lorient"=>"Lorient",
"brest"=>"Brest",
 ], 
 '11071619' => [
 "dijon"=>"Dijon",
"besançon"=>"Besançon",
"belfort"=>"Belfort",
 ], 
 '11071620' => [
 "poitiers"=>"Poitiers",
"pessac"=>"Pessac",
"pau"=>"Pau",
"niort"=>"Niort",
"mérignac"=>"Mérignac",
"limoges"=>"Limoges",
"la-rochelle"=>"La Rochelle",
"brive-la-gaillarde"=>"Brive-la-Gaillarde",
"bordeaux"=>"Bordeaux",
 ], 
 '11071621' => [
 "rouen"=>"Rouen",
"le-havre"=>"Le Havre",
"évreux"=>"Évreux",
"caen"=>"Caen",
 ], 
 '11071622' => [
 "troyes"=>"Troyes",
"strasbourg"=>"Strasbourg",
"reims"=>"Reims",
"nancy"=>"Nancy",
"mulhouse"=>"Mulhouse",
"metz"=>"Metz",
"colmar"=>"Colmar",
"charleville-mézières"=>"Charleville-Mézières",
"châlons-en-champagne"=>"Châlons-en-Champagne",
 ], 
 '11071623' => [
 "toulouse"=>"Toulouse",
"tarbes"=>"Tarbes",
"perpignan"=>"Perpignan",
"nîmes"=>"Nîmes",
"narbonne"=>"Narbonne",
"montpellier"=>"Montpellier",
"montauban"=>"Montauban",
"béziers"=>"Béziers",
"albi"=>"Albi",
 ], 
 '11071624' => [
 "tourcoing"=>"Tourcoing",
"saint-quentin"=>"Saint-Quentin",
"roubaix"=>"Roubaix",
"lille"=>"Lille",
"dunkerque"=>"Dunkerque",
"calais"=>"Calais",
"beauvais"=>"Beauvais",
"amiens"=>"Amiens",
"villeneuve-dascq"=>"Villeneuve-d\'Ascq",
 ], 
 '11071625' => [
 "villeurbanne"=>"Villeurbanne",
"vénissieux"=>"Vénissieux",
"valence"=>"Valence",
"saint-étienne"=>"Saint-Étienne",
"lyon"=>"Lyon",
"grenoble"=>"Grenoble",
"clermont-ferrand"=>"Clermont-Ferrand",
"chambéry"=>"Chambéry",
 ], 
];