<?php 

  return [
  '2523119' => [
 "vittoria"=>"Vittoria",
"trapani"=>"Trapani",
"siracusa"=>"Siracusa",
"ragusa"=>"Ragusa",
"palermo"=>"Palermo",
"messina"=>"Messina",
"marsala"=>"Marsala",
"gela"=>"Gela",
"catania"=>"Catania",
"caltanissetta"=>"Caltanissetta",
"bagheria"=>"Bagheria",
 ], 
 '2523228' => [
 "quartu-santelena"=>"Quartu Sant\'Elena",
"cagliari"=>"Cagliari",
"sassari"=>"Sassari",
 ], 
 '2525468' => [
 "reggio-calabria"=>"Reggio Calabria",
"nicastro-sambiase"=>"Nicastro-Sambiase",
"cosenza"=>"Cosenza",
"catanzaro"=>"Catanzaro",
"lamezia-terme"=>"Lamezia Terme",
 ], 
 '3164604' => [
 "vicenza"=>"Vicenza",
"verona"=>"Verona",
"venice"=>"Venice",
"treviso"=>"Treviso",
"padova"=>"Padova",
"mestre"=>"Mestre",
 ], 
 '3165048' => [
 "terni"=>"Terni",
"perugia"=>"Perugia",
 ], 
 '3165244' => [
 "trento"=>"Trento",
"bolzano"=>"Bolzano",
 ], 
 '3165361' => [
 "prato"=>"Prato",
"pistoia"=>"Pistoia",
"pisa"=>"Pisa",
"massa"=>"Massa",
"lucca"=>"Lucca",
"livorno"=>"Livorno",
"grosseto"=>"Grosseto",
"florence"=>"Florence",
"carrara"=>"Carrara",
"arezzo"=>"Arezzo",
 ], 
 '3169778' => [
 "trani"=>"Trani",
"taranto"=>"Taranto",
"san-severo"=>"San Severo",
"molfetta"=>"Molfetta",
"manfredonia"=>"Manfredonia",
"lecce"=>"Lecce",
"foggia"=>"Foggia",
"cerignola"=>"Cerignola",
"brindisi"=>"Brindisi",
"bitonto"=>"Bitonto",
"bisceglie"=>"Bisceglie",
"barletta"=>"Barletta",
"bari"=>"Bari",
"andria"=>"Andria",
"altamura"=>"Altamura",
 ], 
 '3170831' => [
 "turin"=>"Turin",
"novara"=>"Novara",
"asti"=>"Asti",
"alessandria"=>"Alessandria",
 ], 
 '3174004' => [
 "pesaro"=>"Pesaro",
"ancona"=>"Ancona",
 ], 
 '3174618' => [
 "vigevano"=>"Vigevano",
"varese"=>"Varese",
"sesto-san-giovanni"=>"Sesto San Giovanni",
"pavia"=>"Pavia",
"monza"=>"Monza",
"milano"=>"Milano",
"legnano"=>"Legnano",
"gallarate"=>"Gallarate",
"cremona"=>"Cremona",
"como"=>"Como",
"cinisello-balsamo"=>"Cinisello Balsamo",
"busto-arsizio"=>"Busto Arsizio",
"brescia"=>"Brescia",
"bergamo"=>"Bergamo",
 ], 
 '3174725' => [
 "savona"=>"Savona",
"la-spezia"=>"La Spezia",
"genoa"=>"Genoa",
 ], 
 '3174976' => [
 "rome"=>"Rome",
"lido-di-ostia"=>"Lido di Ostia",
"latina"=>"Latina",
"acilia-castel-fusano-ostia-antica"=>"Acilia-Castel Fusano-Ostia Antica",
"guidonia-montecelio"=>"Guidonia Montecelio",
 ], 
 '3176525' => [
 "udine"=>"Udine",
"trieste"=>"Trieste",
 ], 
 '3177401' => [
 "rimini"=>"Rimini",
"reggio-nellemilia"=>"Reggio nell\'Emilia",
"ravenna"=>"Ravenna",
"piacenza"=>"Piacenza",
"parma"=>"Parma",
"modena"=>"Modena",
"imola"=>"Imola",
"forlì"=>"Forlì",
"ferrara"=>"Ferrara",
"cesena"=>"Cesena",
"carpi-centro"=>"Carpi Centro",
"bologna"=>"Bologna",
 ], 
 '3181042' => [
 "torre-del-greco"=>"Torre del Greco",
"salerno"=>"Salerno",
"portici"=>"Portici",
"napoli"=>"Napoli",
"giugliano-in-campania"=>"Giugliano in Campania",
"ercolano"=>"Ercolano",
"castellammare-di-stabia"=>"Castellammare di Stabia",
"casoria"=>"Casoria",
"caserta"=>"Caserta",
"aversa"=>"Aversa",
"afragola"=>"Afragola",
"acerra"=>"Acerra",
 ], 
 '3182306' => [
 "potenza"=>"Potenza",
"matera"=>"Matera",
 ], 
 '3183560' => [
 "pescara"=>"Pescara",
 ], 
];