<?php 

  return [
  '2743698' => [
 "zoetermeer"=>"Zoetermeer",
"vlaardingen"=>"Vlaardingen",
"spijkenisse"=>"Spijkenisse",
"the-hague"=>"The Hague",
"schiedam"=>"Schiedam",
"rotterdam"=>"Rotterdam",
"leiden"=>"Leiden",
"gouda"=>"Gouda",
"dordrecht"=>"Dordrecht",
"delft"=>"Delft",
"delfshaven"=>"Delfshaven",
"capelle-aan-den-ijssel"=>"Capelle aan den IJssel",
"alphen-aan-den-rijn"=>"Alphen aan den Rijn",
 ], 
 '2745909' => [
 "zeist"=>"Zeist",
"veenendaal"=>"Veenendaal",
"utrecht"=>"Utrecht",
"nieuwegein"=>"Nieuwegein",
"amersfoort"=>"Amersfoort",
 ], 
 '2748838' => [
 "zwolle"=>"Zwolle",
"hengelo"=>"Hengelo",
"hardenberg"=>"Hardenberg",
"enschede"=>"Enschede",
"deventer"=>"Deventer",
"almelo"=>"Almelo",
 ], 
 '2749879' => [
 "zaanstad"=>"Zaanstad",
"zaandam"=>"Zaandam",
"velsen-zuid"=>"Velsen-Zuid",
"purmerend"=>"Purmerend",
"hoorn"=>"Hoorn",
"hoofddorp"=>"Hoofddorp",
"hilversum"=>"Hilversum",
"haarlem"=>"Haarlem",
"den-helder"=>"Den Helder",
"amsterdam"=>"Amsterdam",
"amstelveen"=>"Amstelveen",
"alkmaar"=>"Alkmaar",
"amsterdam-zuidoost"=>"Amsterdam-Zuidoost",
 ], 
 '2749990' => [
 "tilburg"=>"Tilburg",
"s-hertogenbosch"=>"\'s-Hertogenbosch",
"roosendaal"=>"Roosendaal",
"oss"=>"Oss",
"oosterhout"=>"Oosterhout",
"helmond"=>"Helmond",
"eindhoven"=>"Eindhoven",
"breda"=>"Breda",
"bergen-op-zoom"=>"Bergen op Zoom",
 ], 
 '2751596' => [
 "venlo"=>"Venlo",
"maastricht"=>"Maastricht",
"heerlen"=>"Heerlen",
"born"=>"Born",
 ], 
 '2755249' => [
 "groningen"=>"Groningen",
 ], 
 '2755634' => [
 "nijmegen"=>"Nijmegen",
"ede"=>"Ede",
"arnhem"=>"Arnhem",
"apeldoorn"=>"Apeldoorn",
 ], 
 '2755812' => [
 "leeuwarden"=>"Leeuwarden",
 ], 
 '2756631' => [
 "emmen"=>"Emmen",
"assen"=>"Assen",
 ], 
 '3319179' => [
 "lelystad"=>"Lelystad",
"almere-stad"=>"Almere Stad",
 ], 
];