<?php 

  return [
  '858785' => [
 "zamość"=>"Zamość",
"lublin"=>"Lublin",
"chełm"=>"Chełm",
"biała-podlaska"=>"Biała Podlaska",
 ], 
 '858786' => [
 "tarnów"=>"Tarnów",
"nowy-sącz"=>"Nowy Sącz",
"kraków"=>"Kraków",
 ], 
 '858787' => [
 "żoliborz"=>"Żoliborz",
"wola"=>"Wola",
"wawer"=>"Wawer",
"warsaw"=>"Warsaw",
"targówek"=>"Targówek",
"śródmieście"=>"Śródmieście",
"siedlce"=>"Siedlce",
"radom"=>"Radom",
"pruszków"=>"Pruszków",
"ostrołęka"=>"Ostrołęka",
"ochota"=>"Ochota",
"mokotów"=>"Mokotów",
"legionowo"=>"Legionowo",
"bielany"=>"Bielany",
"białołeka"=>"Białołeka",
"bemowo"=>"Bemowo",
"płock"=>"Płock",
"ursynów"=>"Ursynów",
"praga-północ"=>"Praga Północ",
"praga-południe"=>"Praga Południe",
 ], 
 '858788' => [
 "tarnobrzeg"=>"Tarnobrzeg",
"stalowa-wola"=>"Stalowa Wola",
"rzeszów"=>"Rzeszów",
"przemyśl"=>"Przemyśl",
"mielec"=>"Mielec",
 ], 
 '858789' => [
 "suwałki"=>"Suwałki",
"łomża"=>"Łomża",
"białystok"=>"Białystok",
 ], 
 '858790' => [
 "starachowice"=>"Starachowice",
"ostrowiec-świętokrzyski"=>"Ostrowiec Świętokrzyski",
"kielce"=>"Kielce",
 ], 
 '858791' => [
 "olsztyn"=>"Olsztyn",
"ełk"=>"Ełk",
"elbląg"=>"Elbląg",
 ], 
 '3337492' => [
 "wrocław"=>"Wrocław",
"wałbrzych"=>"Wałbrzych",
"świdnica"=>"Świdnica",
"lubin"=>"Lubin",
"legnica"=>"Legnica",
"jelenia-góra"=>"Jelenia Góra",
"głogów"=>"Głogów",
 ], 
 '3337493' => [
 "tomaszów-mazowiecki"=>"Tomaszów Mazowiecki",
"zgierz"=>"Zgierz",
"piotrków-trybunalski"=>"Piotrków Trybunalski",
"pabianice"=>"Pabianice",
"łódź"=>"Łódź",
"bełchatów"=>"Bełchatów",
 ], 
 '3337494' => [
 "zielona-góra"=>"Zielona Góra",
"gorzów-wielkopolski"=>"Gorzów Wielkopolski",
 ], 
 '3337495' => [
 "opole"=>"Opole",
"kędzierzyn-koźle"=>"Kędzierzyn-Koźle",
 ], 
 '3337496' => [
 "tczew"=>"Tczew",
"słupsk"=>"Słupsk",
"gdynia"=>"Gdynia",
"gdańsk"=>"Gdańsk",
 ], 
 '3337497' => [
 "żory"=>"Żory",
"zawiercie"=>"Zawiercie",
"zabrze"=>"Zabrze",
"tychy"=>"Tychy",
"tarnowskie-góry"=>"Tarnowskie Góry",
"świętochłowice"=>"Świętochłowice",
"sosnowiec"=>"Sosnowiec",
"siemianowice-śląskie"=>"Siemianowice Śląskie",
"rybnik"=>"Rybnik",
"ruda-śląska"=>"Ruda Śląska",
"racibórz"=>"Racibórz",
"piekary-śląskie"=>"Piekary Śląskie",
"mysłowice"=>"Mysłowice",
"katowice"=>"Katowice",
"jaworzno"=>"Jaworzno",
"jastrzębie-zdrój"=>"Jastrzębie Zdrój",
"gliwice"=>"Gliwice",
"dąbrowa-górnicza"=>"Dąbrowa Górnicza",
"częstochowa"=>"Częstochowa",
"chorzów"=>"Chorzów",
"bytom"=>"Bytom",
"bielsko-biala"=>"Bielsko-Biala",
"będzin"=>"Będzin",
 ], 
 '3337498' => [
 "poznań"=>"Poznań",
"piła"=>"Piła",
"ostrów-wielkopolski"=>"Ostrów Wielkopolski",
"leszno"=>"Leszno",
"konin"=>"Konin",
"kalisz"=>"Kalisz",
"gniezno"=>"Gniezno",
 ], 
 '3337499' => [
 "szczecin"=>"Szczecin",
"stargard-szczeciński"=>"Stargard Szczeciński",
"koszalin"=>"Koszalin",
 ], 
 '3337500' => [
 "włocławek"=>"Włocławek",
"toruń"=>"Toruń",
"inowrocław"=>"Inowrocław",
"grudziądz"=>"Grudziądz",
"fordon"=>"Fordon",
"bydgoszcz"=>"Bydgoszcz",
 ], 
];