<?php 

  return [
 "focșani"=>"Focșani",
"râmnicu_vâlcea"=>"Râmnicu Vâlcea",
"vaslui"=>"Vaslui",
"tulcea"=>"Tulcea",
"timişoara"=>"Timişoara",
"suceava"=>"Suceava",
"sibiu"=>"Sibiu",
"satu_mare"=>"Satu Mare",
"zalău"=>"Zalău",
"ploieşti"=>"Ploieşti",
"slatina"=>"Slatina",
"roman"=>"Roman",
"târgu-mureş"=>"Târgu-Mureş",
"drobeta-turnu_severin"=>"Drobeta-Turnu Severin",
"baia_mare"=>"Baia Mare",
"iaşi"=>"Iaşi",
"slobozia"=>"Slobozia",
"hunedoara"=>"Hunedoara",
"târgu_jiu"=>"Târgu Jiu",
"giurgiu"=>"Giurgiu",
"galaţi"=>"Galaţi",
"craiova"=>"Craiova",
"târgovişte"=>"Târgovişte",
"sfântu-gheorghe"=>"Sfântu-Gheorghe",
"constanţa"=>"Constanţa",
"turda"=>"Turda",
"reşiţa"=>"Reşiţa",
"buzău"=>"Buzău",
"bucharest"=>"Bucharest",
"braşov"=>"Braşov",
"brăila"=>"Brăila",
"botoşani"=>"Botoşani",
"bistriţa"=>"Bistriţa",
"oradea"=>"Oradea",
"bacău"=>"Bacău",
"piteşti"=>"Piteşti",
"arad"=>"Arad",
"alba_iulia"=>"Alba Iulia",
];