<?php 

  return [
 "focșani_city"=>"Focșani",
"râmnicu_vâlcea_city"=>"Râmnicu Vâlcea",
"vaslui_city"=>"Vaslui",
"tulcea_city"=>"Tulcea",
"timişoara_city"=>"Timişoara",
"suceava_city"=>"Suceava",
"sibiu_city"=>"Sibiu",
"satu_mare_city"=>"Satu Mare",
"zalău_city"=>"Zalău",
"ploieşti_city"=>"Ploieşti",
"slatina_city"=>"Slatina",
"roman_city"=>"Roman",
"târgu-mureş_city"=>"Târgu-Mureş",
"drobeta-turnu_severin_city"=>"Drobeta-Turnu Severin",
"baia_mare_city"=>"Baia Mare",
"iaşi_city"=>"Iaşi",
"slobozia_city"=>"Slobozia",
"hunedoara_city"=>"Hunedoara",
"târgu_jiu_city"=>"Târgu Jiu",
"giurgiu_city"=>"Giurgiu",
"galaţi_city"=>"Galaţi",
"craiova_city"=>"Craiova",
"târgovişte_city"=>"Târgovişte",
"sfântu-gheorghe_city"=>"Sfântu-Gheorghe",
"constanţa_city"=>"Constanţa",
"turda_city"=>"Turda",
"reşiţa_city"=>"Reşiţa",
"buzău_city"=>"Buzău",
"bucharest_city"=>"Bucharest",
"braşov_city"=>"Braşov",
"brăila_city"=>"Brăila",
"botoşani_city"=>"Botoşani",
"bistriţa_city"=>"Bistriţa",
"oradea_city"=>"Oradea",
"bacău_city"=>"Bacău",
"piteşti_city"=>"Piteşti",
"arad_city"=>"Arad",
"alba_iulia_city"=>"Alba Iulia",
];