<?php 

  return [
 "zhytomyr"=>"Zhytomyr",
"zaporizhzhya"=>"Zaporizhzhya",
"uzhhorod"=>"Uzhhorod",
"novovolyns’k"=>"Novovolyns’k",
"vinnytsya"=>"Vinnytsya",
"ternopil’"=>"Ternopil’",
"sumy"=>"Sumy",
"sevastopol"=>"Sevastopol",
"rivne"=>"Rivne",
"poltava"=>"Poltava",
"odessa"=>"Odessa",
"pervomays’k"=>"Pervomays’k",
"stryi"=>"Stryi",
"syevyerodonets’k"=>"Syevyerodonets’k",
"fastiv"=>"Fastiv",
"kyiv"=>"Kyiv",
"yevpatoriya"=>"Yevpatoriya",
"oleksandriya"=>"Oleksandriya",
"khmel’nyts’kyy"=>"Khmel’nyts’kyy",
"nova_kakhovka"=>"Nova Kakhovka",
"lozova"=>"Lozova",
"kolomyya"=>"Kolomyya",
"druzhkivka"=>"Druzhkivka",
"zhovti_vody"=>"Zhovti Vody",
"chernivtsi"=>"Chernivtsi",
"pryluky"=>"Pryluky",
"uman’"=>"Uman’",
];