<?php 

  return [
 "zhytomyr_city"=>"Zhytomyr",
"zaporizhzhya_city"=>"Zaporizhzhya",
"uzhhorod_city"=>"Uzhhorod",
"novovolyns’k_city"=>"Novovolyns’k",
"vinnytsya_city"=>"Vinnytsya",
"ternopil’_city"=>"Ternopil’",
"sumy_city"=>"Sumy",
"sevastopol_city"=>"Sevastopol",
"rivne_city"=>"Rivne",
"poltava_city"=>"Poltava",
"odessa_city"=>"Odessa",
"pervomays’k_city"=>"Pervomays’k",
"stryi_city"=>"Stryi",
"syevyerodonets’k_city"=>"Syevyerodonets’k",
"fastiv_city"=>"Fastiv",
"kyiv_city"=>"Kyiv",
"yevpatoriya_city"=>"Yevpatoriya",
"oleksandriya_city"=>"Oleksandriya",
"khmel’nyts’kyy_city"=>"Khmel’nyts’kyy",
"nova_kakhovka_city"=>"Nova Kakhovka",
"lozova_city"=>"Lozova",
"kolomyya_city"=>"Kolomyya",
"druzhkivka_city"=>"Druzhkivka",
"zhovti_vody_city"=>"Zhovti Vody",
"chernivtsi_city"=>"Chernivtsi",
"pryluky_city"=>"Pryluky",
"uman’_city"=>"Uman’",
];