<?php

  return [
      "razgrad"=>"Разград",
      "montana"=>"Монтана",
      "vratsa"=>"Враца",
      "varna"=>"Варна",
      "dobrich"=>"Добрич",
      "sofia-province"=>"Софийская область",
      "ruse"=>"Уловка",
      "plovdiv"=>"Пловдив",
      "pleven"=>"плевен",
      "pernik"=>"Перник",
      "pazardzhik"=>"Пазарджик",
      "lovech"=>"Ловеч",
      "sofia"=>"София",
      "burgas"=>"Бургас",
      "blagoevgrad"=>"Благоевград",
      "gabrovo"=>"Габрово",
      "kardzhali"=>"Кырджали",
      "kyustendil"=>"Кюстендил",
      "shumen"=>"Шумен",
      "silistra"=>"Силистра",
      "sliven"=>"Сливен",
      "smolyan"=>"Смолян",
      "stara-zagora"=>"Стара Загора",
      "targovishte"=>"Тарговиште",
      "veliko-tarnovo"=>"Велико Тырново",
      "vidin"=>"Видин",
      "yambol"=>"Ямбол",
];
