<?php 

  return [
 'zurich'=>'Цюрих',
 'vaud'=>'Во',
 'valais'=>'Вале',
 'uri'=>'Ури',
 'ticino'=>'Тичино',
 'thurgau'=>'Тургау',
 'solothurn'=>'Золотурн',
 'schwyz'=>'Швиц',
 'schaffhausen'=>'Шаффхаузен',
 'saint-gallen'=>'Санкт-Галлен',
 'obwalden'=>'Обвальден',
 'nidwalden'=>'Нидвальден',
 'neuchâtel'=>'Невшатель',
 'lucerne'=>'Люцерна',
 'jura'=>'Юра',
 'grisons'=>'Гризоны',
 'glarus'=>'Гларус',
 'geneva'=>'Женева',
 'fribourg'=>'Фрибург',
 'bern'=>'Берн',
 'basel-city'=>'Базель Сити',
 'basel-landschaft'=>'Базель Ланд',
 'appenzell-ausserrhoden'=>'Аппенцелль Ауссерроден',
 'appenzell-innerrhoden'=>'Аппенцелль Иннерроден',
 'aargau'=>'Ааргау',
 'zug'=>'Цуг',
 ];