<?php 

  return [
 'pays_de_la_loire'=>'Плати Луары',
 'corsica'=>'Корсика',
 'brittany'=>'Бретань',
 'burgundy'=>'бордовый',
 'aquitaine'=>'Аквитания',
 'lower_normandy'=>'Нижняя Нормандия',
 'alsace'=>'Эльзас',
 'languedoc-roussillon'=>'Лангедок-Руссильон',
 'nord-pas-de-calais'=>'Север-Па-де-Кале',
 'auvergne'=>'Овернь',
 'rhône-alpes'=>'Рона-Альпы',
 'poitou-charentes'=>'Пуату-Шарант',
 'picardie'=>'Пикардия',
 'midi-pyrénées'=>'Юг-Пиренеи',
 'lorraine'=>'Лотарингия',
 'limousin'=>'Лимузен',
 'upper_normandy'=>'Верхняя Нормандия',
 'franche-comté'=>'Франш-Конте',
 'champagne-ardenne'=>'Шампанское-Арденны',
 'île-de-france'=>'Иль-де-Франс',
 'centre'=>'Центр',
 'provence-alpes-côte_d\'azur'=>'Прованс-Альпы-Лазурный Берег',
 ];