<?php

  return [
      "rožaje"=>"Рожае",
      "žabljak"=>"Жабляк",
      "ulcinj"=>"Улцинь",
      "tivat"=>"Тиват",
      "podgorica"=>"Подгорица",
      "šavnik"=>"Шавник",
      "plužine"=>"Плужине",
      "pljevlja"=>"Плевля",
      "plav"=>"Плав",
      "nikšić"=>"Никшич",
      "mojkovac"=>"Мойковац",
      "kotor"=>"Котор",
      "kolašin"=>"Колашин",
      "berane"=>"Беране",
      "herceg-novi"=>"Герцег-Нови",
      "danilovgrad"=>"Даниловград",
      "cetinje"=>"Цетинье",
      "budva"=>"Будва",
      "bijelo-polje"=>"Биело Поле",
      "bar"=>"Бар",
      "andrijevica"=>"Андриевица",
      "gusinje"=>"Гусине",
      "petnjica"=>"Петница",
];
